// ========== DO NOT EDIT THIS FILE! AUTO GENERATED!!! =========
package list

import (
	"errors"
	"fmt"

	"github.com/kaytu-io/cli-program/pkg"
	kaytuSDK "github.com/kaytu-io/cli-program/pkg/api/kaytu"
	"github.com/kaytu-io/cli-program/pkg/api/kaytu/client/workspace"
	"github.com/spf13/cobra"
)

var WorkspacesCmd = &cobra.Command{
	Use: "workspaces",
	RunE: func(cmd *cobra.Command, args []string) error {

		client, auth, err := kaytuSDK.GetKaytuAuthClient(cmd)
		if err != nil {
			if errors.Is(err, pkg.ExpiredSession) {
				fmt.Println(err.Error())
				return nil
			}
			panic(err)
		}

		req := workspace.NewGetWorkspaceAPIV1WorkspacesParams()

		resp, err := client.Workspace.GetWorkspaceAPIV1Workspaces(req, auth)
		if err != nil {
			return fmt.Errorf("[GetWorkspaceAPIV1Workspaces] : %v", err)
		}

		err = pkg.PrintOutput(cmd, "GetWorkspaceAPIV1Workspaces", resp.GetPayload())
		if err != nil {
			return fmt.Errorf("[GetWorkspaceAPIV1Workspaces] : %v", err)
		}

		return nil

	},
}

func init() {

}
