// Code generated by go-swagger; DO NOT EDIT.

package insights

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetComplianceAPIV1MetadataTagInsightKeyParams creates a new GetComplianceAPIV1MetadataTagInsightKeyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetComplianceAPIV1MetadataTagInsightKeyParams() *GetComplianceAPIV1MetadataTagInsightKeyParams {
	return &GetComplianceAPIV1MetadataTagInsightKeyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetComplianceAPIV1MetadataTagInsightKeyParamsWithTimeout creates a new GetComplianceAPIV1MetadataTagInsightKeyParams object
// with the ability to set a timeout on a request.
func NewGetComplianceAPIV1MetadataTagInsightKeyParamsWithTimeout(timeout time.Duration) *GetComplianceAPIV1MetadataTagInsightKeyParams {
	return &GetComplianceAPIV1MetadataTagInsightKeyParams{
		timeout: timeout,
	}
}

// NewGetComplianceAPIV1MetadataTagInsightKeyParamsWithContext creates a new GetComplianceAPIV1MetadataTagInsightKeyParams object
// with the ability to set a context for a request.
func NewGetComplianceAPIV1MetadataTagInsightKeyParamsWithContext(ctx context.Context) *GetComplianceAPIV1MetadataTagInsightKeyParams {
	return &GetComplianceAPIV1MetadataTagInsightKeyParams{
		Context: ctx,
	}
}

// NewGetComplianceAPIV1MetadataTagInsightKeyParamsWithHTTPClient creates a new GetComplianceAPIV1MetadataTagInsightKeyParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetComplianceAPIV1MetadataTagInsightKeyParamsWithHTTPClient(client *http.Client) *GetComplianceAPIV1MetadataTagInsightKeyParams {
	return &GetComplianceAPIV1MetadataTagInsightKeyParams{
		HTTPClient: client,
	}
}

/*
GetComplianceAPIV1MetadataTagInsightKeyParams contains all the parameters to send to the API endpoint

	for the get compliance API v1 metadata tag insight key operation.

	Typically these are written to a http.Request.
*/
type GetComplianceAPIV1MetadataTagInsightKeyParams struct {

	/* Key.

	   Tag key
	*/
	Key string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get compliance API v1 metadata tag insight key params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetComplianceAPIV1MetadataTagInsightKeyParams) WithDefaults() *GetComplianceAPIV1MetadataTagInsightKeyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get compliance API v1 metadata tag insight key params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetComplianceAPIV1MetadataTagInsightKeyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get compliance API v1 metadata tag insight key params
func (o *GetComplianceAPIV1MetadataTagInsightKeyParams) WithTimeout(timeout time.Duration) *GetComplianceAPIV1MetadataTagInsightKeyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get compliance API v1 metadata tag insight key params
func (o *GetComplianceAPIV1MetadataTagInsightKeyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get compliance API v1 metadata tag insight key params
func (o *GetComplianceAPIV1MetadataTagInsightKeyParams) WithContext(ctx context.Context) *GetComplianceAPIV1MetadataTagInsightKeyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get compliance API v1 metadata tag insight key params
func (o *GetComplianceAPIV1MetadataTagInsightKeyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get compliance API v1 metadata tag insight key params
func (o *GetComplianceAPIV1MetadataTagInsightKeyParams) WithHTTPClient(client *http.Client) *GetComplianceAPIV1MetadataTagInsightKeyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get compliance API v1 metadata tag insight key params
func (o *GetComplianceAPIV1MetadataTagInsightKeyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithKey adds the key to the get compliance API v1 metadata tag insight key params
func (o *GetComplianceAPIV1MetadataTagInsightKeyParams) WithKey(key string) *GetComplianceAPIV1MetadataTagInsightKeyParams {
	o.SetKey(key)
	return o
}

// SetKey adds the key to the get compliance API v1 metadata tag insight key params
func (o *GetComplianceAPIV1MetadataTagInsightKeyParams) SetKey(key string) {
	o.Key = key
}

// WriteToRequest writes these params to a swagger request
func (o *GetComplianceAPIV1MetadataTagInsightKeyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param key
	if err := r.SetPathParam("key", o.Key); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
