// ========== DO NOT EDIT THIS FILE! AUTO GENERATED!!! =========
package resource_collections

import (
	"errors"
	"fmt"

	"github.com/kaytu-io/cli-program/cmd/flags"
	"github.com/kaytu-io/cli-program/pkg"
	kaytuSDK "github.com/kaytu-io/cli-program/pkg/api/kaytu"
	"github.com/kaytu-io/cli-program/pkg/api/kaytu/client/resource_collection"
	"github.com/spf13/cobra"
)

var MetadataCmd = &cobra.Command{
	Use: "metadata",
	RunE: func(cmd *cobra.Command, args []string) error {

		client, auth, err := kaytuSDK.GetKaytuAuthClient(cmd)
		if err != nil {
			if errors.Is(err, pkg.ExpiredSession) {
				fmt.Println(err.Error())
				return nil
			}
			panic(err)
		}

		req := resource_collection.NewGetInventoryAPIV2MetadataResourceCollectionParams()

		req.SetID(flags.ReadStringArrayFlag(cmd, "ID"))

		req.SetStatus(flags.ReadStringArrayFlag(cmd, "Status"))

		resp, err := client.ResourceCollection.GetInventoryAPIV2MetadataResourceCollection(req, auth)
		if err != nil {
			return fmt.Errorf("[GetInventoryAPIV2MetadataResourceCollection] : %v", err)
		}

		err = pkg.PrintOutput(cmd, "GetInventoryAPIV2MetadataResourceCollection", resp.GetPayload())
		if err != nil {
			return fmt.Errorf("[GetInventoryAPIV2MetadataResourceCollection] : %v", err)
		}

		return nil

	},
}

func init() {

	MetadataCmd.Flags().StringArray("id", nil, "Resource collection IDs")

	MetadataCmd.Flags().StringArray("status", nil, "Resource collection status")

}
