// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kaytu-io/cli-program/pkg/api/kaytu/models"
)

// GetAuthAPIV1UserRoleBindingsReader is a Reader for the GetAuthAPIV1UserRoleBindings structure.
type GetAuthAPIV1UserRoleBindingsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAuthAPIV1UserRoleBindingsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAuthAPIV1UserRoleBindingsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /auth/api/v1/user/role/bindings] GetAuthAPIV1UserRoleBindings", response, response.Code())
	}
}

// NewGetAuthAPIV1UserRoleBindingsOK creates a GetAuthAPIV1UserRoleBindingsOK with default headers values
func NewGetAuthAPIV1UserRoleBindingsOK() *GetAuthAPIV1UserRoleBindingsOK {
	return &GetAuthAPIV1UserRoleBindingsOK{}
}

/*
GetAuthAPIV1UserRoleBindingsOK describes a response with status code 200, with default header values.

OK
*/
type GetAuthAPIV1UserRoleBindingsOK struct {
	Payload *models.GithubComKaytuIoKaytuEnginePkgAuthAPIGetRoleBindingsResponse
}

// IsSuccess returns true when this get auth Api v1 user role bindings o k response has a 2xx status code
func (o *GetAuthAPIV1UserRoleBindingsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get auth Api v1 user role bindings o k response has a 3xx status code
func (o *GetAuthAPIV1UserRoleBindingsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get auth Api v1 user role bindings o k response has a 4xx status code
func (o *GetAuthAPIV1UserRoleBindingsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get auth Api v1 user role bindings o k response has a 5xx status code
func (o *GetAuthAPIV1UserRoleBindingsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get auth Api v1 user role bindings o k response a status code equal to that given
func (o *GetAuthAPIV1UserRoleBindingsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get auth Api v1 user role bindings o k response
func (o *GetAuthAPIV1UserRoleBindingsOK) Code() int {
	return 200
}

func (o *GetAuthAPIV1UserRoleBindingsOK) Error() string {
	return fmt.Sprintf("[GET /auth/api/v1/user/role/bindings][%d] getAuthApiV1UserRoleBindingsOK  %+v", 200, o.Payload)
}

func (o *GetAuthAPIV1UserRoleBindingsOK) String() string {
	return fmt.Sprintf("[GET /auth/api/v1/user/role/bindings][%d] getAuthApiV1UserRoleBindingsOK  %+v", 200, o.Payload)
}

func (o *GetAuthAPIV1UserRoleBindingsOK) GetPayload() *models.GithubComKaytuIoKaytuEnginePkgAuthAPIGetRoleBindingsResponse {
	return o.Payload
}

func (o *GetAuthAPIV1UserRoleBindingsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComKaytuIoKaytuEnginePkgAuthAPIGetRoleBindingsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
