// Code generated by go-swagger; DO NOT EDIT.

package describe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kaytu-io/cli-program/pkg/api/kaytu/models"
)

// GetScheduleAPIV1InsightJobJobIDReader is a Reader for the GetScheduleAPIV1InsightJobJobID structure.
type GetScheduleAPIV1InsightJobJobIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetScheduleAPIV1InsightJobJobIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetScheduleAPIV1InsightJobJobIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /schedule/api/v1/insight/job/{jobId}] GetScheduleAPIV1InsightJobJobID", response, response.Code())
	}
}

// NewGetScheduleAPIV1InsightJobJobIDOK creates a GetScheduleAPIV1InsightJobJobIDOK with default headers values
func NewGetScheduleAPIV1InsightJobJobIDOK() *GetScheduleAPIV1InsightJobJobIDOK {
	return &GetScheduleAPIV1InsightJobJobIDOK{}
}

/*
GetScheduleAPIV1InsightJobJobIDOK describes a response with status code 200, with default header values.

OK
*/
type GetScheduleAPIV1InsightJobJobIDOK struct {
	Payload *models.GithubComKaytuIoKaytuEnginePkgDescribeAPIInsightJob
}

// IsSuccess returns true when this get schedule Api v1 insight job job Id o k response has a 2xx status code
func (o *GetScheduleAPIV1InsightJobJobIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get schedule Api v1 insight job job Id o k response has a 3xx status code
func (o *GetScheduleAPIV1InsightJobJobIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get schedule Api v1 insight job job Id o k response has a 4xx status code
func (o *GetScheduleAPIV1InsightJobJobIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get schedule Api v1 insight job job Id o k response has a 5xx status code
func (o *GetScheduleAPIV1InsightJobJobIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get schedule Api v1 insight job job Id o k response a status code equal to that given
func (o *GetScheduleAPIV1InsightJobJobIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get schedule Api v1 insight job job Id o k response
func (o *GetScheduleAPIV1InsightJobJobIDOK) Code() int {
	return 200
}

func (o *GetScheduleAPIV1InsightJobJobIDOK) Error() string {
	return fmt.Sprintf("[GET /schedule/api/v1/insight/job/{jobId}][%d] getScheduleApiV1InsightJobJobIdOK  %+v", 200, o.Payload)
}

func (o *GetScheduleAPIV1InsightJobJobIDOK) String() string {
	return fmt.Sprintf("[GET /schedule/api/v1/insight/job/{jobId}][%d] getScheduleApiV1InsightJobJobIdOK  %+v", 200, o.Payload)
}

func (o *GetScheduleAPIV1InsightJobJobIDOK) GetPayload() *models.GithubComKaytuIoKaytuEnginePkgDescribeAPIInsightJob {
	return o.Payload
}

func (o *GetScheduleAPIV1InsightJobJobIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComKaytuIoKaytuEnginePkgDescribeAPIInsightJob)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
