// Code generated by go-swagger; DO NOT EDIT.

package describe

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kaytu-io/cli-program/pkg/api/kaytu/models"
)

// NewPostScheduleAPIV1StacksInsightTriggerParams creates a new PostScheduleAPIV1StacksInsightTriggerParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostScheduleAPIV1StacksInsightTriggerParams() *PostScheduleAPIV1StacksInsightTriggerParams {
	return &PostScheduleAPIV1StacksInsightTriggerParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostScheduleAPIV1StacksInsightTriggerParamsWithTimeout creates a new PostScheduleAPIV1StacksInsightTriggerParams object
// with the ability to set a timeout on a request.
func NewPostScheduleAPIV1StacksInsightTriggerParamsWithTimeout(timeout time.Duration) *PostScheduleAPIV1StacksInsightTriggerParams {
	return &PostScheduleAPIV1StacksInsightTriggerParams{
		timeout: timeout,
	}
}

// NewPostScheduleAPIV1StacksInsightTriggerParamsWithContext creates a new PostScheduleAPIV1StacksInsightTriggerParams object
// with the ability to set a context for a request.
func NewPostScheduleAPIV1StacksInsightTriggerParamsWithContext(ctx context.Context) *PostScheduleAPIV1StacksInsightTriggerParams {
	return &PostScheduleAPIV1StacksInsightTriggerParams{
		Context: ctx,
	}
}

// NewPostScheduleAPIV1StacksInsightTriggerParamsWithHTTPClient creates a new PostScheduleAPIV1StacksInsightTriggerParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostScheduleAPIV1StacksInsightTriggerParamsWithHTTPClient(client *http.Client) *PostScheduleAPIV1StacksInsightTriggerParams {
	return &PostScheduleAPIV1StacksInsightTriggerParams{
		HTTPClient: client,
	}
}

/*
PostScheduleAPIV1StacksInsightTriggerParams contains all the parameters to send to the API endpoint

	for the post schedule API v1 stacks insight trigger operation.

	Typically these are written to a http.Request.
*/
type PostScheduleAPIV1StacksInsightTriggerParams struct {

	/* Request.

	   Request Body
	*/
	Request models.GithubComKaytuIoKaytuEnginePkgDescribeAPIStackInsightRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post schedule API v1 stacks insight trigger params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostScheduleAPIV1StacksInsightTriggerParams) WithDefaults() *PostScheduleAPIV1StacksInsightTriggerParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post schedule API v1 stacks insight trigger params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostScheduleAPIV1StacksInsightTriggerParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post schedule API v1 stacks insight trigger params
func (o *PostScheduleAPIV1StacksInsightTriggerParams) WithTimeout(timeout time.Duration) *PostScheduleAPIV1StacksInsightTriggerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post schedule API v1 stacks insight trigger params
func (o *PostScheduleAPIV1StacksInsightTriggerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post schedule API v1 stacks insight trigger params
func (o *PostScheduleAPIV1StacksInsightTriggerParams) WithContext(ctx context.Context) *PostScheduleAPIV1StacksInsightTriggerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post schedule API v1 stacks insight trigger params
func (o *PostScheduleAPIV1StacksInsightTriggerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post schedule API v1 stacks insight trigger params
func (o *PostScheduleAPIV1StacksInsightTriggerParams) WithHTTPClient(client *http.Client) *PostScheduleAPIV1StacksInsightTriggerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post schedule API v1 stacks insight trigger params
func (o *PostScheduleAPIV1StacksInsightTriggerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the post schedule API v1 stacks insight trigger params
func (o *PostScheduleAPIV1StacksInsightTriggerParams) WithRequest(request models.GithubComKaytuIoKaytuEnginePkgDescribeAPIStackInsightRequest) *PostScheduleAPIV1StacksInsightTriggerParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post schedule API v1 stacks insight trigger params
func (o *PostScheduleAPIV1StacksInsightTriggerParams) SetRequest(request models.GithubComKaytuIoKaytuEnginePkgDescribeAPIStackInsightRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PostScheduleAPIV1StacksInsightTriggerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
