// ========== DO NOT EDIT THIS FILE! AUTO GENERATED!!! =========
package delete

import (
	"errors"
	"fmt"

	"github.com/kaytu-io/cli-program/cmd/flags"
	"github.com/kaytu-io/cli-program/pkg"
	kaytuSDK "github.com/kaytu-io/cli-program/pkg/api/kaytu"
	"github.com/kaytu-io/cli-program/pkg/api/kaytu/client/onboard"
	"github.com/spf13/cobra"
)

var AccountCmd = &cobra.Command{
	Use: "account",
	RunE: func(cmd *cobra.Command, args []string) error {

		client, auth, err := kaytuSDK.GetKaytuAuthClient(cmd)
		if err != nil {
			if errors.Is(err, pkg.ExpiredSession) {
				fmt.Println(err.Error())
				return nil
			}
			panic(err)
		}

		req := onboard.NewDeleteOnboardAPIV1SourceSourceIDParams()

		req.SetSourceID(flags.ReadStringFlag(cmd, "SourceID"))

		resp, err := client.Onboard.DeleteOnboardAPIV1SourceSourceID(req, auth)
		if err != nil {
			return fmt.Errorf("[DeleteOnboardAPIV1SourceSourceID] : %v", err)
		}

		_ = resp

		return nil

	},
}

func init() {

	AccountCmd.Flags().String("source-id", "", "Source ID")

	AccountCmd.MarkFlagRequired("source-id")

}
