// Code generated by go-swagger; DO NOT EDIT.

package analytics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetInventoryAPIV2AnalyticsMetricParams creates a new GetInventoryAPIV2AnalyticsMetricParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetInventoryAPIV2AnalyticsMetricParams() *GetInventoryAPIV2AnalyticsMetricParams {
	return &GetInventoryAPIV2AnalyticsMetricParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetInventoryAPIV2AnalyticsMetricParamsWithTimeout creates a new GetInventoryAPIV2AnalyticsMetricParams object
// with the ability to set a timeout on a request.
func NewGetInventoryAPIV2AnalyticsMetricParamsWithTimeout(timeout time.Duration) *GetInventoryAPIV2AnalyticsMetricParams {
	return &GetInventoryAPIV2AnalyticsMetricParams{
		timeout: timeout,
	}
}

// NewGetInventoryAPIV2AnalyticsMetricParamsWithContext creates a new GetInventoryAPIV2AnalyticsMetricParams object
// with the ability to set a context for a request.
func NewGetInventoryAPIV2AnalyticsMetricParamsWithContext(ctx context.Context) *GetInventoryAPIV2AnalyticsMetricParams {
	return &GetInventoryAPIV2AnalyticsMetricParams{
		Context: ctx,
	}
}

// NewGetInventoryAPIV2AnalyticsMetricParamsWithHTTPClient creates a new GetInventoryAPIV2AnalyticsMetricParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetInventoryAPIV2AnalyticsMetricParamsWithHTTPClient(client *http.Client) *GetInventoryAPIV2AnalyticsMetricParams {
	return &GetInventoryAPIV2AnalyticsMetricParams{
		HTTPClient: client,
	}
}

/*
GetInventoryAPIV2AnalyticsMetricParams contains all the parameters to send to the API endpoint

	for the get inventory API v2 analytics metric operation.

	Typically these are written to a http.Request.
*/
type GetInventoryAPIV2AnalyticsMetricParams struct {

	/* ConnectionGroup.

	   Connection group to filter by - mutually exclusive with connectionId
	*/
	ConnectionGroup []string

	/* ConnectionID.

	   Connection IDs to filter by - mutually exclusive with connectionGroup
	*/
	ConnectionID []string

	/* Connector.

	   Connector type to filter by
	*/
	Connector []string

	/* EndTime.

	   timestamp for resource count in epoch seconds
	*/
	EndTime *int64

	/* MetricIDs.

	   Metric IDs
	*/
	MetricIDs []string

	/* MetricType.

	   Metric type, default: assets
	*/
	MetricType *string

	/* MinCount.

	   Minimum number of resources with this tag value, default 0
	*/
	MinCount *int64

	/* PageNumber.

	   page number - default is 1
	*/
	PageNumber *int64

	/* PageSize.

	   page size - default is 20
	*/
	PageSize *int64

	/* ResourceCollection.

	   Resource collection IDs to filter by
	*/
	ResourceCollection []string

	/* SortBy.

	   Sort by field - default is count
	*/
	SortBy *string

	/* StartTime.

	   timestamp for resource count change comparison in epoch seconds
	*/
	StartTime *int64

	/* Tag.

	   Key-Value tags in key=value format to filter by
	*/
	Tag []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get inventory API v2 analytics metric params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInventoryAPIV2AnalyticsMetricParams) WithDefaults() *GetInventoryAPIV2AnalyticsMetricParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get inventory API v2 analytics metric params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInventoryAPIV2AnalyticsMetricParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get inventory API v2 analytics metric params
func (o *GetInventoryAPIV2AnalyticsMetricParams) WithTimeout(timeout time.Duration) *GetInventoryAPIV2AnalyticsMetricParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get inventory API v2 analytics metric params
func (o *GetInventoryAPIV2AnalyticsMetricParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get inventory API v2 analytics metric params
func (o *GetInventoryAPIV2AnalyticsMetricParams) WithContext(ctx context.Context) *GetInventoryAPIV2AnalyticsMetricParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get inventory API v2 analytics metric params
func (o *GetInventoryAPIV2AnalyticsMetricParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get inventory API v2 analytics metric params
func (o *GetInventoryAPIV2AnalyticsMetricParams) WithHTTPClient(client *http.Client) *GetInventoryAPIV2AnalyticsMetricParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get inventory API v2 analytics metric params
func (o *GetInventoryAPIV2AnalyticsMetricParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithConnectionGroup adds the connectionGroup to the get inventory API v2 analytics metric params
func (o *GetInventoryAPIV2AnalyticsMetricParams) WithConnectionGroup(connectionGroup []string) *GetInventoryAPIV2AnalyticsMetricParams {
	o.SetConnectionGroup(connectionGroup)
	return o
}

// SetConnectionGroup adds the connectionGroup to the get inventory API v2 analytics metric params
func (o *GetInventoryAPIV2AnalyticsMetricParams) SetConnectionGroup(connectionGroup []string) {
	o.ConnectionGroup = connectionGroup
}

// WithConnectionID adds the connectionID to the get inventory API v2 analytics metric params
func (o *GetInventoryAPIV2AnalyticsMetricParams) WithConnectionID(connectionID []string) *GetInventoryAPIV2AnalyticsMetricParams {
	o.SetConnectionID(connectionID)
	return o
}

// SetConnectionID adds the connectionId to the get inventory API v2 analytics metric params
func (o *GetInventoryAPIV2AnalyticsMetricParams) SetConnectionID(connectionID []string) {
	o.ConnectionID = connectionID
}

// WithConnector adds the connector to the get inventory API v2 analytics metric params
func (o *GetInventoryAPIV2AnalyticsMetricParams) WithConnector(connector []string) *GetInventoryAPIV2AnalyticsMetricParams {
	o.SetConnector(connector)
	return o
}

// SetConnector adds the connector to the get inventory API v2 analytics metric params
func (o *GetInventoryAPIV2AnalyticsMetricParams) SetConnector(connector []string) {
	o.Connector = connector
}

// WithEndTime adds the endTime to the get inventory API v2 analytics metric params
func (o *GetInventoryAPIV2AnalyticsMetricParams) WithEndTime(endTime *int64) *GetInventoryAPIV2AnalyticsMetricParams {
	o.SetEndTime(endTime)
	return o
}

// SetEndTime adds the endTime to the get inventory API v2 analytics metric params
func (o *GetInventoryAPIV2AnalyticsMetricParams) SetEndTime(endTime *int64) {
	o.EndTime = endTime
}

// WithMetricIDs adds the metricIDs to the get inventory API v2 analytics metric params
func (o *GetInventoryAPIV2AnalyticsMetricParams) WithMetricIDs(metricIDs []string) *GetInventoryAPIV2AnalyticsMetricParams {
	o.SetMetricIDs(metricIDs)
	return o
}

// SetMetricIDs adds the metricIDs to the get inventory API v2 analytics metric params
func (o *GetInventoryAPIV2AnalyticsMetricParams) SetMetricIDs(metricIDs []string) {
	o.MetricIDs = metricIDs
}

// WithMetricType adds the metricType to the get inventory API v2 analytics metric params
func (o *GetInventoryAPIV2AnalyticsMetricParams) WithMetricType(metricType *string) *GetInventoryAPIV2AnalyticsMetricParams {
	o.SetMetricType(metricType)
	return o
}

// SetMetricType adds the metricType to the get inventory API v2 analytics metric params
func (o *GetInventoryAPIV2AnalyticsMetricParams) SetMetricType(metricType *string) {
	o.MetricType = metricType
}

// WithMinCount adds the minCount to the get inventory API v2 analytics metric params
func (o *GetInventoryAPIV2AnalyticsMetricParams) WithMinCount(minCount *int64) *GetInventoryAPIV2AnalyticsMetricParams {
	o.SetMinCount(minCount)
	return o
}

// SetMinCount adds the minCount to the get inventory API v2 analytics metric params
func (o *GetInventoryAPIV2AnalyticsMetricParams) SetMinCount(minCount *int64) {
	o.MinCount = minCount
}

// WithPageNumber adds the pageNumber to the get inventory API v2 analytics metric params
func (o *GetInventoryAPIV2AnalyticsMetricParams) WithPageNumber(pageNumber *int64) *GetInventoryAPIV2AnalyticsMetricParams {
	o.SetPageNumber(pageNumber)
	return o
}

// SetPageNumber adds the pageNumber to the get inventory API v2 analytics metric params
func (o *GetInventoryAPIV2AnalyticsMetricParams) SetPageNumber(pageNumber *int64) {
	o.PageNumber = pageNumber
}

// WithPageSize adds the pageSize to the get inventory API v2 analytics metric params
func (o *GetInventoryAPIV2AnalyticsMetricParams) WithPageSize(pageSize *int64) *GetInventoryAPIV2AnalyticsMetricParams {
	o.SetPageSize(pageSize)
	return o
}

// SetPageSize adds the pageSize to the get inventory API v2 analytics metric params
func (o *GetInventoryAPIV2AnalyticsMetricParams) SetPageSize(pageSize *int64) {
	o.PageSize = pageSize
}

// WithResourceCollection adds the resourceCollection to the get inventory API v2 analytics metric params
func (o *GetInventoryAPIV2AnalyticsMetricParams) WithResourceCollection(resourceCollection []string) *GetInventoryAPIV2AnalyticsMetricParams {
	o.SetResourceCollection(resourceCollection)
	return o
}

// SetResourceCollection adds the resourceCollection to the get inventory API v2 analytics metric params
func (o *GetInventoryAPIV2AnalyticsMetricParams) SetResourceCollection(resourceCollection []string) {
	o.ResourceCollection = resourceCollection
}

// WithSortBy adds the sortBy to the get inventory API v2 analytics metric params
func (o *GetInventoryAPIV2AnalyticsMetricParams) WithSortBy(sortBy *string) *GetInventoryAPIV2AnalyticsMetricParams {
	o.SetSortBy(sortBy)
	return o
}

// SetSortBy adds the sortBy to the get inventory API v2 analytics metric params
func (o *GetInventoryAPIV2AnalyticsMetricParams) SetSortBy(sortBy *string) {
	o.SortBy = sortBy
}

// WithStartTime adds the startTime to the get inventory API v2 analytics metric params
func (o *GetInventoryAPIV2AnalyticsMetricParams) WithStartTime(startTime *int64) *GetInventoryAPIV2AnalyticsMetricParams {
	o.SetStartTime(startTime)
	return o
}

// SetStartTime adds the startTime to the get inventory API v2 analytics metric params
func (o *GetInventoryAPIV2AnalyticsMetricParams) SetStartTime(startTime *int64) {
	o.StartTime = startTime
}

// WithTag adds the tag to the get inventory API v2 analytics metric params
func (o *GetInventoryAPIV2AnalyticsMetricParams) WithTag(tag []string) *GetInventoryAPIV2AnalyticsMetricParams {
	o.SetTag(tag)
	return o
}

// SetTag adds the tag to the get inventory API v2 analytics metric params
func (o *GetInventoryAPIV2AnalyticsMetricParams) SetTag(tag []string) {
	o.Tag = tag
}

// WriteToRequest writes these params to a swagger request
func (o *GetInventoryAPIV2AnalyticsMetricParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ConnectionGroup != nil {

		// binding items for connectionGroup
		joinedConnectionGroup := o.bindParamConnectionGroup(reg)

		// query array param connectionGroup
		if err := r.SetQueryParam("connectionGroup", joinedConnectionGroup...); err != nil {
			return err
		}
	}

	if o.ConnectionID != nil {

		// binding items for connectionId
		joinedConnectionID := o.bindParamConnectionID(reg)

		// query array param connectionId
		if err := r.SetQueryParam("connectionId", joinedConnectionID...); err != nil {
			return err
		}
	}

	if o.Connector != nil {

		// binding items for connector
		joinedConnector := o.bindParamConnector(reg)

		// query array param connector
		if err := r.SetQueryParam("connector", joinedConnector...); err != nil {
			return err
		}
	}

	if o.EndTime != nil {

		// query param endTime
		var qrEndTime int64

		if o.EndTime != nil {
			qrEndTime = *o.EndTime
		}
		qEndTime := swag.FormatInt64(qrEndTime)
		if qEndTime != "" {

			if err := r.SetQueryParam("endTime", qEndTime); err != nil {
				return err
			}
		}
	}

	if o.MetricIDs != nil {

		// binding items for metricIDs
		joinedMetricIDs := o.bindParamMetricIDs(reg)

		// query array param metricIDs
		if err := r.SetQueryParam("metricIDs", joinedMetricIDs...); err != nil {
			return err
		}
	}

	if o.MetricType != nil {

		// query param metricType
		var qrMetricType string

		if o.MetricType != nil {
			qrMetricType = *o.MetricType
		}
		qMetricType := qrMetricType
		if qMetricType != "" {

			if err := r.SetQueryParam("metricType", qMetricType); err != nil {
				return err
			}
		}
	}

	if o.MinCount != nil {

		// query param minCount
		var qrMinCount int64

		if o.MinCount != nil {
			qrMinCount = *o.MinCount
		}
		qMinCount := swag.FormatInt64(qrMinCount)
		if qMinCount != "" {

			if err := r.SetQueryParam("minCount", qMinCount); err != nil {
				return err
			}
		}
	}

	if o.PageNumber != nil {

		// query param pageNumber
		var qrPageNumber int64

		if o.PageNumber != nil {
			qrPageNumber = *o.PageNumber
		}
		qPageNumber := swag.FormatInt64(qrPageNumber)
		if qPageNumber != "" {

			if err := r.SetQueryParam("pageNumber", qPageNumber); err != nil {
				return err
			}
		}
	}

	if o.PageSize != nil {

		// query param pageSize
		var qrPageSize int64

		if o.PageSize != nil {
			qrPageSize = *o.PageSize
		}
		qPageSize := swag.FormatInt64(qrPageSize)
		if qPageSize != "" {

			if err := r.SetQueryParam("pageSize", qPageSize); err != nil {
				return err
			}
		}
	}

	if o.ResourceCollection != nil {

		// binding items for resourceCollection
		joinedResourceCollection := o.bindParamResourceCollection(reg)

		// query array param resourceCollection
		if err := r.SetQueryParam("resourceCollection", joinedResourceCollection...); err != nil {
			return err
		}
	}

	if o.SortBy != nil {

		// query param sortBy
		var qrSortBy string

		if o.SortBy != nil {
			qrSortBy = *o.SortBy
		}
		qSortBy := qrSortBy
		if qSortBy != "" {

			if err := r.SetQueryParam("sortBy", qSortBy); err != nil {
				return err
			}
		}
	}

	if o.StartTime != nil {

		// query param startTime
		var qrStartTime int64

		if o.StartTime != nil {
			qrStartTime = *o.StartTime
		}
		qStartTime := swag.FormatInt64(qrStartTime)
		if qStartTime != "" {

			if err := r.SetQueryParam("startTime", qStartTime); err != nil {
				return err
			}
		}
	}

	if o.Tag != nil {

		// binding items for tag
		joinedTag := o.bindParamTag(reg)

		// query array param tag
		if err := r.SetQueryParam("tag", joinedTag...); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamGetInventoryAPIV2AnalyticsMetric binds the parameter connectionGroup
func (o *GetInventoryAPIV2AnalyticsMetricParams) bindParamConnectionGroup(formats strfmt.Registry) []string {
	connectionGroupIR := o.ConnectionGroup

	var connectionGroupIC []string
	for _, connectionGroupIIR := range connectionGroupIR { // explode []string

		connectionGroupIIV := connectionGroupIIR // string as string
		connectionGroupIC = append(connectionGroupIC, connectionGroupIIV)
	}

	// items.CollectionFormat: "csv"
	connectionGroupIS := swag.JoinByFormat(connectionGroupIC, "csv")

	return connectionGroupIS
}

// bindParamGetInventoryAPIV2AnalyticsMetric binds the parameter connectionId
func (o *GetInventoryAPIV2AnalyticsMetricParams) bindParamConnectionID(formats strfmt.Registry) []string {
	connectionIDIR := o.ConnectionID

	var connectionIDIC []string
	for _, connectionIDIIR := range connectionIDIR { // explode []string

		connectionIDIIV := connectionIDIIR // string as string
		connectionIDIC = append(connectionIDIC, connectionIDIIV)
	}

	// items.CollectionFormat: "csv"
	connectionIDIS := swag.JoinByFormat(connectionIDIC, "csv")

	return connectionIDIS
}

// bindParamGetInventoryAPIV2AnalyticsMetric binds the parameter connector
func (o *GetInventoryAPIV2AnalyticsMetricParams) bindParamConnector(formats strfmt.Registry) []string {
	connectorIR := o.Connector

	var connectorIC []string
	for _, connectorIIR := range connectorIR { // explode []string

		connectorIIV := connectorIIR // string as string
		connectorIC = append(connectorIC, connectorIIV)
	}

	// items.CollectionFormat: "csv"
	connectorIS := swag.JoinByFormat(connectorIC, "csv")

	return connectorIS
}

// bindParamGetInventoryAPIV2AnalyticsMetric binds the parameter metricIDs
func (o *GetInventoryAPIV2AnalyticsMetricParams) bindParamMetricIDs(formats strfmt.Registry) []string {
	metricIDsIR := o.MetricIDs

	var metricIDsIC []string
	for _, metricIDsIIR := range metricIDsIR { // explode []string

		metricIDsIIV := metricIDsIIR // string as string
		metricIDsIC = append(metricIDsIC, metricIDsIIV)
	}

	// items.CollectionFormat: "csv"
	metricIDsIS := swag.JoinByFormat(metricIDsIC, "csv")

	return metricIDsIS
}

// bindParamGetInventoryAPIV2AnalyticsMetric binds the parameter resourceCollection
func (o *GetInventoryAPIV2AnalyticsMetricParams) bindParamResourceCollection(formats strfmt.Registry) []string {
	resourceCollectionIR := o.ResourceCollection

	var resourceCollectionIC []string
	for _, resourceCollectionIIR := range resourceCollectionIR { // explode []string

		resourceCollectionIIV := resourceCollectionIIR // string as string
		resourceCollectionIC = append(resourceCollectionIC, resourceCollectionIIV)
	}

	// items.CollectionFormat: "csv"
	resourceCollectionIS := swag.JoinByFormat(resourceCollectionIC, "csv")

	return resourceCollectionIS
}

// bindParamGetInventoryAPIV2AnalyticsMetric binds the parameter tag
func (o *GetInventoryAPIV2AnalyticsMetricParams) bindParamTag(formats strfmt.Registry) []string {
	tagIR := o.Tag

	var tagIC []string
	for _, tagIIR := range tagIR { // explode []string

		tagIIV := tagIIR // string as string
		tagIC = append(tagIC, tagIIV)
	}

	// items.CollectionFormat: "csv"
	tagIS := swag.JoinByFormat(tagIC, "csv")

	return tagIS
}
