// Code generated by go-swagger; DO NOT EDIT.

package analytics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetInventoryAPIV2AnalyticsMetricsMetricIDParams creates a new GetInventoryAPIV2AnalyticsMetricsMetricIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetInventoryAPIV2AnalyticsMetricsMetricIDParams() *GetInventoryAPIV2AnalyticsMetricsMetricIDParams {
	return &GetInventoryAPIV2AnalyticsMetricsMetricIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetInventoryAPIV2AnalyticsMetricsMetricIDParamsWithTimeout creates a new GetInventoryAPIV2AnalyticsMetricsMetricIDParams object
// with the ability to set a timeout on a request.
func NewGetInventoryAPIV2AnalyticsMetricsMetricIDParamsWithTimeout(timeout time.Duration) *GetInventoryAPIV2AnalyticsMetricsMetricIDParams {
	return &GetInventoryAPIV2AnalyticsMetricsMetricIDParams{
		timeout: timeout,
	}
}

// NewGetInventoryAPIV2AnalyticsMetricsMetricIDParamsWithContext creates a new GetInventoryAPIV2AnalyticsMetricsMetricIDParams object
// with the ability to set a context for a request.
func NewGetInventoryAPIV2AnalyticsMetricsMetricIDParamsWithContext(ctx context.Context) *GetInventoryAPIV2AnalyticsMetricsMetricIDParams {
	return &GetInventoryAPIV2AnalyticsMetricsMetricIDParams{
		Context: ctx,
	}
}

// NewGetInventoryAPIV2AnalyticsMetricsMetricIDParamsWithHTTPClient creates a new GetInventoryAPIV2AnalyticsMetricsMetricIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetInventoryAPIV2AnalyticsMetricsMetricIDParamsWithHTTPClient(client *http.Client) *GetInventoryAPIV2AnalyticsMetricsMetricIDParams {
	return &GetInventoryAPIV2AnalyticsMetricsMetricIDParams{
		HTTPClient: client,
	}
}

/*
GetInventoryAPIV2AnalyticsMetricsMetricIDParams contains all the parameters to send to the API endpoint

	for the get inventory API v2 analytics metrics metric ID operation.

	Typically these are written to a http.Request.
*/
type GetInventoryAPIV2AnalyticsMetricsMetricIDParams struct {

	/* MetricID.

	   MetricID
	*/
	MetricID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get inventory API v2 analytics metrics metric ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInventoryAPIV2AnalyticsMetricsMetricIDParams) WithDefaults() *GetInventoryAPIV2AnalyticsMetricsMetricIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get inventory API v2 analytics metrics metric ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInventoryAPIV2AnalyticsMetricsMetricIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get inventory API v2 analytics metrics metric ID params
func (o *GetInventoryAPIV2AnalyticsMetricsMetricIDParams) WithTimeout(timeout time.Duration) *GetInventoryAPIV2AnalyticsMetricsMetricIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get inventory API v2 analytics metrics metric ID params
func (o *GetInventoryAPIV2AnalyticsMetricsMetricIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get inventory API v2 analytics metrics metric ID params
func (o *GetInventoryAPIV2AnalyticsMetricsMetricIDParams) WithContext(ctx context.Context) *GetInventoryAPIV2AnalyticsMetricsMetricIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get inventory API v2 analytics metrics metric ID params
func (o *GetInventoryAPIV2AnalyticsMetricsMetricIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get inventory API v2 analytics metrics metric ID params
func (o *GetInventoryAPIV2AnalyticsMetricsMetricIDParams) WithHTTPClient(client *http.Client) *GetInventoryAPIV2AnalyticsMetricsMetricIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get inventory API v2 analytics metrics metric ID params
func (o *GetInventoryAPIV2AnalyticsMetricsMetricIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithMetricID adds the metricID to the get inventory API v2 analytics metrics metric ID params
func (o *GetInventoryAPIV2AnalyticsMetricsMetricIDParams) WithMetricID(metricID string) *GetInventoryAPIV2AnalyticsMetricsMetricIDParams {
	o.SetMetricID(metricID)
	return o
}

// SetMetricID adds the metricId to the get inventory API v2 analytics metrics metric ID params
func (o *GetInventoryAPIV2AnalyticsMetricsMetricIDParams) SetMetricID(metricID string) {
	o.MetricID = metricID
}

// WriteToRequest writes these params to a swagger request
func (o *GetInventoryAPIV2AnalyticsMetricsMetricIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param metric_id
	if err := r.SetPathParam("metric_id", o.MetricID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
