// Code generated by go-swagger; DO NOT EDIT.

package analytics

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetInventoryAPIV2AnalyticsSpendCompositionParams creates a new GetInventoryAPIV2AnalyticsSpendCompositionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetInventoryAPIV2AnalyticsSpendCompositionParams() *GetInventoryAPIV2AnalyticsSpendCompositionParams {
	return &GetInventoryAPIV2AnalyticsSpendCompositionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetInventoryAPIV2AnalyticsSpendCompositionParamsWithTimeout creates a new GetInventoryAPIV2AnalyticsSpendCompositionParams object
// with the ability to set a timeout on a request.
func NewGetInventoryAPIV2AnalyticsSpendCompositionParamsWithTimeout(timeout time.Duration) *GetInventoryAPIV2AnalyticsSpendCompositionParams {
	return &GetInventoryAPIV2AnalyticsSpendCompositionParams{
		timeout: timeout,
	}
}

// NewGetInventoryAPIV2AnalyticsSpendCompositionParamsWithContext creates a new GetInventoryAPIV2AnalyticsSpendCompositionParams object
// with the ability to set a context for a request.
func NewGetInventoryAPIV2AnalyticsSpendCompositionParamsWithContext(ctx context.Context) *GetInventoryAPIV2AnalyticsSpendCompositionParams {
	return &GetInventoryAPIV2AnalyticsSpendCompositionParams{
		Context: ctx,
	}
}

// NewGetInventoryAPIV2AnalyticsSpendCompositionParamsWithHTTPClient creates a new GetInventoryAPIV2AnalyticsSpendCompositionParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetInventoryAPIV2AnalyticsSpendCompositionParamsWithHTTPClient(client *http.Client) *GetInventoryAPIV2AnalyticsSpendCompositionParams {
	return &GetInventoryAPIV2AnalyticsSpendCompositionParams{
		HTTPClient: client,
	}
}

/*
GetInventoryAPIV2AnalyticsSpendCompositionParams contains all the parameters to send to the API endpoint

	for the get inventory API v2 analytics spend composition operation.

	Typically these are written to a http.Request.
*/
type GetInventoryAPIV2AnalyticsSpendCompositionParams struct {

	/* ConnectionGroup.

	   Connection group to filter by - mutually exclusive with connectionId
	*/
	ConnectionGroup []string

	/* ConnectionID.

	   Connection IDs to filter by - mutually exclusive with connectionGroup
	*/
	ConnectionID []string

	/* Connector.

	   Connector type to filter by
	*/
	Connector []string

	/* EndTime.

	   timestamp for end in epoch seconds
	*/
	EndTime *int64

	/* StartTime.

	   timestamp for start in epoch seconds
	*/
	StartTime *int64

	/* Top.

	   How many top values to return default is 5
	*/
	Top *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get inventory API v2 analytics spend composition params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInventoryAPIV2AnalyticsSpendCompositionParams) WithDefaults() *GetInventoryAPIV2AnalyticsSpendCompositionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get inventory API v2 analytics spend composition params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInventoryAPIV2AnalyticsSpendCompositionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get inventory API v2 analytics spend composition params
func (o *GetInventoryAPIV2AnalyticsSpendCompositionParams) WithTimeout(timeout time.Duration) *GetInventoryAPIV2AnalyticsSpendCompositionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get inventory API v2 analytics spend composition params
func (o *GetInventoryAPIV2AnalyticsSpendCompositionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get inventory API v2 analytics spend composition params
func (o *GetInventoryAPIV2AnalyticsSpendCompositionParams) WithContext(ctx context.Context) *GetInventoryAPIV2AnalyticsSpendCompositionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get inventory API v2 analytics spend composition params
func (o *GetInventoryAPIV2AnalyticsSpendCompositionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get inventory API v2 analytics spend composition params
func (o *GetInventoryAPIV2AnalyticsSpendCompositionParams) WithHTTPClient(client *http.Client) *GetInventoryAPIV2AnalyticsSpendCompositionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get inventory API v2 analytics spend composition params
func (o *GetInventoryAPIV2AnalyticsSpendCompositionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithConnectionGroup adds the connectionGroup to the get inventory API v2 analytics spend composition params
func (o *GetInventoryAPIV2AnalyticsSpendCompositionParams) WithConnectionGroup(connectionGroup []string) *GetInventoryAPIV2AnalyticsSpendCompositionParams {
	o.SetConnectionGroup(connectionGroup)
	return o
}

// SetConnectionGroup adds the connectionGroup to the get inventory API v2 analytics spend composition params
func (o *GetInventoryAPIV2AnalyticsSpendCompositionParams) SetConnectionGroup(connectionGroup []string) {
	o.ConnectionGroup = connectionGroup
}

// WithConnectionID adds the connectionID to the get inventory API v2 analytics spend composition params
func (o *GetInventoryAPIV2AnalyticsSpendCompositionParams) WithConnectionID(connectionID []string) *GetInventoryAPIV2AnalyticsSpendCompositionParams {
	o.SetConnectionID(connectionID)
	return o
}

// SetConnectionID adds the connectionId to the get inventory API v2 analytics spend composition params
func (o *GetInventoryAPIV2AnalyticsSpendCompositionParams) SetConnectionID(connectionID []string) {
	o.ConnectionID = connectionID
}

// WithConnector adds the connector to the get inventory API v2 analytics spend composition params
func (o *GetInventoryAPIV2AnalyticsSpendCompositionParams) WithConnector(connector []string) *GetInventoryAPIV2AnalyticsSpendCompositionParams {
	o.SetConnector(connector)
	return o
}

// SetConnector adds the connector to the get inventory API v2 analytics spend composition params
func (o *GetInventoryAPIV2AnalyticsSpendCompositionParams) SetConnector(connector []string) {
	o.Connector = connector
}

// WithEndTime adds the endTime to the get inventory API v2 analytics spend composition params
func (o *GetInventoryAPIV2AnalyticsSpendCompositionParams) WithEndTime(endTime *int64) *GetInventoryAPIV2AnalyticsSpendCompositionParams {
	o.SetEndTime(endTime)
	return o
}

// SetEndTime adds the endTime to the get inventory API v2 analytics spend composition params
func (o *GetInventoryAPIV2AnalyticsSpendCompositionParams) SetEndTime(endTime *int64) {
	o.EndTime = endTime
}

// WithStartTime adds the startTime to the get inventory API v2 analytics spend composition params
func (o *GetInventoryAPIV2AnalyticsSpendCompositionParams) WithStartTime(startTime *int64) *GetInventoryAPIV2AnalyticsSpendCompositionParams {
	o.SetStartTime(startTime)
	return o
}

// SetStartTime adds the startTime to the get inventory API v2 analytics spend composition params
func (o *GetInventoryAPIV2AnalyticsSpendCompositionParams) SetStartTime(startTime *int64) {
	o.StartTime = startTime
}

// WithTop adds the top to the get inventory API v2 analytics spend composition params
func (o *GetInventoryAPIV2AnalyticsSpendCompositionParams) WithTop(top *int64) *GetInventoryAPIV2AnalyticsSpendCompositionParams {
	o.SetTop(top)
	return o
}

// SetTop adds the top to the get inventory API v2 analytics spend composition params
func (o *GetInventoryAPIV2AnalyticsSpendCompositionParams) SetTop(top *int64) {
	o.Top = top
}

// WriteToRequest writes these params to a swagger request
func (o *GetInventoryAPIV2AnalyticsSpendCompositionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ConnectionGroup != nil {

		// binding items for connectionGroup
		joinedConnectionGroup := o.bindParamConnectionGroup(reg)

		// query array param connectionGroup
		if err := r.SetQueryParam("connectionGroup", joinedConnectionGroup...); err != nil {
			return err
		}
	}

	if o.ConnectionID != nil {

		// binding items for connectionId
		joinedConnectionID := o.bindParamConnectionID(reg)

		// query array param connectionId
		if err := r.SetQueryParam("connectionId", joinedConnectionID...); err != nil {
			return err
		}
	}

	if o.Connector != nil {

		// binding items for connector
		joinedConnector := o.bindParamConnector(reg)

		// query array param connector
		if err := r.SetQueryParam("connector", joinedConnector...); err != nil {
			return err
		}
	}

	if o.EndTime != nil {

		// query param endTime
		var qrEndTime int64

		if o.EndTime != nil {
			qrEndTime = *o.EndTime
		}
		qEndTime := swag.FormatInt64(qrEndTime)
		if qEndTime != "" {

			if err := r.SetQueryParam("endTime", qEndTime); err != nil {
				return err
			}
		}
	}

	if o.StartTime != nil {

		// query param startTime
		var qrStartTime int64

		if o.StartTime != nil {
			qrStartTime = *o.StartTime
		}
		qStartTime := swag.FormatInt64(qrStartTime)
		if qStartTime != "" {

			if err := r.SetQueryParam("startTime", qStartTime); err != nil {
				return err
			}
		}
	}

	if o.Top != nil {

		// query param top
		var qrTop int64

		if o.Top != nil {
			qrTop = *o.Top
		}
		qTop := swag.FormatInt64(qrTop)
		if qTop != "" {

			if err := r.SetQueryParam("top", qTop); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamGetInventoryAPIV2AnalyticsSpendComposition binds the parameter connectionGroup
func (o *GetInventoryAPIV2AnalyticsSpendCompositionParams) bindParamConnectionGroup(formats strfmt.Registry) []string {
	connectionGroupIR := o.ConnectionGroup

	var connectionGroupIC []string
	for _, connectionGroupIIR := range connectionGroupIR { // explode []string

		connectionGroupIIV := connectionGroupIIR // string as string
		connectionGroupIC = append(connectionGroupIC, connectionGroupIIV)
	}

	// items.CollectionFormat: "csv"
	connectionGroupIS := swag.JoinByFormat(connectionGroupIC, "csv")

	return connectionGroupIS
}

// bindParamGetInventoryAPIV2AnalyticsSpendComposition binds the parameter connectionId
func (o *GetInventoryAPIV2AnalyticsSpendCompositionParams) bindParamConnectionID(formats strfmt.Registry) []string {
	connectionIDIR := o.ConnectionID

	var connectionIDIC []string
	for _, connectionIDIIR := range connectionIDIR { // explode []string

		connectionIDIIV := connectionIDIIR // string as string
		connectionIDIC = append(connectionIDIC, connectionIDIIV)
	}

	// items.CollectionFormat: "csv"
	connectionIDIS := swag.JoinByFormat(connectionIDIC, "csv")

	return connectionIDIS
}

// bindParamGetInventoryAPIV2AnalyticsSpendComposition binds the parameter connector
func (o *GetInventoryAPIV2AnalyticsSpendCompositionParams) bindParamConnector(formats strfmt.Registry) []string {
	connectorIR := o.Connector

	var connectorIC []string
	for _, connectorIIR := range connectorIR { // explode []string

		connectorIIV := connectorIIR // string as string
		connectorIC = append(connectorIC, connectorIIV)
	}

	// items.CollectionFormat: "csv"
	connectorIS := swag.JoinByFormat(connectorIC, "csv")

	return connectorIS
}
