// Code generated by go-swagger; DO NOT EDIT.

package onboard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetOnboardAPIV1SourceAccountAccountIDParams creates a new GetOnboardAPIV1SourceAccountAccountIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetOnboardAPIV1SourceAccountAccountIDParams() *GetOnboardAPIV1SourceAccountAccountIDParams {
	return &GetOnboardAPIV1SourceAccountAccountIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetOnboardAPIV1SourceAccountAccountIDParamsWithTimeout creates a new GetOnboardAPIV1SourceAccountAccountIDParams object
// with the ability to set a timeout on a request.
func NewGetOnboardAPIV1SourceAccountAccountIDParamsWithTimeout(timeout time.Duration) *GetOnboardAPIV1SourceAccountAccountIDParams {
	return &GetOnboardAPIV1SourceAccountAccountIDParams{
		timeout: timeout,
	}
}

// NewGetOnboardAPIV1SourceAccountAccountIDParamsWithContext creates a new GetOnboardAPIV1SourceAccountAccountIDParams object
// with the ability to set a context for a request.
func NewGetOnboardAPIV1SourceAccountAccountIDParamsWithContext(ctx context.Context) *GetOnboardAPIV1SourceAccountAccountIDParams {
	return &GetOnboardAPIV1SourceAccountAccountIDParams{
		Context: ctx,
	}
}

// NewGetOnboardAPIV1SourceAccountAccountIDParamsWithHTTPClient creates a new GetOnboardAPIV1SourceAccountAccountIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetOnboardAPIV1SourceAccountAccountIDParamsWithHTTPClient(client *http.Client) *GetOnboardAPIV1SourceAccountAccountIDParams {
	return &GetOnboardAPIV1SourceAccountAccountIDParams{
		HTTPClient: client,
	}
}

/*
GetOnboardAPIV1SourceAccountAccountIDParams contains all the parameters to send to the API endpoint

	for the get onboard API v1 source account account ID operation.

	Typically these are written to a http.Request.
*/
type GetOnboardAPIV1SourceAccountAccountIDParams struct {

	/* AccountID.

	   SourceID
	*/
	AccountID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get onboard API v1 source account account ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOnboardAPIV1SourceAccountAccountIDParams) WithDefaults() *GetOnboardAPIV1SourceAccountAccountIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get onboard API v1 source account account ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOnboardAPIV1SourceAccountAccountIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get onboard API v1 source account account ID params
func (o *GetOnboardAPIV1SourceAccountAccountIDParams) WithTimeout(timeout time.Duration) *GetOnboardAPIV1SourceAccountAccountIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get onboard API v1 source account account ID params
func (o *GetOnboardAPIV1SourceAccountAccountIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get onboard API v1 source account account ID params
func (o *GetOnboardAPIV1SourceAccountAccountIDParams) WithContext(ctx context.Context) *GetOnboardAPIV1SourceAccountAccountIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get onboard API v1 source account account ID params
func (o *GetOnboardAPIV1SourceAccountAccountIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get onboard API v1 source account account ID params
func (o *GetOnboardAPIV1SourceAccountAccountIDParams) WithHTTPClient(client *http.Client) *GetOnboardAPIV1SourceAccountAccountIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get onboard API v1 source account account ID params
func (o *GetOnboardAPIV1SourceAccountAccountIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the get onboard API v1 source account account ID params
func (o *GetOnboardAPIV1SourceAccountAccountIDParams) WithAccountID(accountID int64) *GetOnboardAPIV1SourceAccountAccountIDParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the get onboard API v1 source account account ID params
func (o *GetOnboardAPIV1SourceAccountAccountIDParams) SetAccountID(accountID int64) {
	o.AccountID = accountID
}

// WriteToRequest writes these params to a swagger request
func (o *GetOnboardAPIV1SourceAccountAccountIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param account_id
	if err := r.SetPathParam("account_id", swag.FormatInt64(o.AccountID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
