// Code generated by go-swagger; DO NOT EDIT.

package onboard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kaytu-io/cli-program/pkg/api/kaytu/models"
)

// GetOnboardAPIV1SourceSourceIDCredentialsReader is a Reader for the GetOnboardAPIV1SourceSourceIDCredentials structure.
type GetOnboardAPIV1SourceSourceIDCredentialsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOnboardAPIV1SourceSourceIDCredentialsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOnboardAPIV1SourceSourceIDCredentialsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetOnboardAPIV1SourceSourceIDCredentialsOK creates a GetOnboardAPIV1SourceSourceIDCredentialsOK with default headers values
func NewGetOnboardAPIV1SourceSourceIDCredentialsOK() *GetOnboardAPIV1SourceSourceIDCredentialsOK {
	return &GetOnboardAPIV1SourceSourceIDCredentialsOK{}
}

/*
GetOnboardAPIV1SourceSourceIDCredentialsOK describes a response with status code 200, with default header values.

OK
*/
type GetOnboardAPIV1SourceSourceIDCredentialsOK struct {
	Payload *models.GitlabComKeibiengineKeibiEnginePkgOnboardAPIAzureCredential
}

// IsSuccess returns true when this get onboard Api v1 source source Id credentials o k response has a 2xx status code
func (o *GetOnboardAPIV1SourceSourceIDCredentialsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get onboard Api v1 source source Id credentials o k response has a 3xx status code
func (o *GetOnboardAPIV1SourceSourceIDCredentialsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get onboard Api v1 source source Id credentials o k response has a 4xx status code
func (o *GetOnboardAPIV1SourceSourceIDCredentialsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get onboard Api v1 source source Id credentials o k response has a 5xx status code
func (o *GetOnboardAPIV1SourceSourceIDCredentialsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get onboard Api v1 source source Id credentials o k response a status code equal to that given
func (o *GetOnboardAPIV1SourceSourceIDCredentialsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get onboard Api v1 source source Id credentials o k response
func (o *GetOnboardAPIV1SourceSourceIDCredentialsOK) Code() int {
	return 200
}

func (o *GetOnboardAPIV1SourceSourceIDCredentialsOK) Error() string {
	return fmt.Sprintf("[GET /onboard/api/v1/source/{sourceId}/credentials][%d] getOnboardApiV1SourceSourceIdCredentialsOK  %+v", 200, o.Payload)
}

func (o *GetOnboardAPIV1SourceSourceIDCredentialsOK) String() string {
	return fmt.Sprintf("[GET /onboard/api/v1/source/{sourceId}/credentials][%d] getOnboardApiV1SourceSourceIdCredentialsOK  %+v", 200, o.Payload)
}

func (o *GetOnboardAPIV1SourceSourceIDCredentialsOK) GetPayload() *models.GitlabComKeibiengineKeibiEnginePkgOnboardAPIAzureCredential {
	return o.Payload
}

func (o *GetOnboardAPIV1SourceSourceIDCredentialsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GitlabComKeibiengineKeibiEnginePkgOnboardAPIAzureCredential)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
