package config

import "github.com/kaytu-io/cli-program/codegen/api"

var commandDef = map[string]string{
	"alerting.DeleteAlertingAPIV1ActionDeleteActionID":                                          "delete automation action",
	"alerting.DeleteAlertingAPIV1RuleDeleteRuleID":                                              "delete automation rule",
	"alerting.GetAlertingAPIV1ActionList":                                                       "list automation actions",
	"alerting.GetAlertingAPIV1RuleList":                                                         "list automation rules",
	"alerting.GetAlertingAPIV1RuleRuleIDTrigger":                                                "",
	"alerting.GetAlertingAPIV1TriggerList":                                                      "list automation alerts",
	"alerting.PostAlertingAPIV1ActionCreate":                                                    "create automation action",
	"alerting.PostAlertingAPIV1ActionJira":                                                      "create automation jira-action",
	"alerting.PostAlertingAPIV1ActionSlack":                                                     "create automation slack-action",
	"alerting.PostAlertingAPIV1RuleCreate":                                                      "create automation rule",
	"alerting.PutAlertingAPIV1ActionUpdateActionID":                                             "",
	"alerting.PutAlertingAPIV1RuleUpdateRuleID":                                                 "",
	"analytics.GetInventoryAPIV2AnalyticsCategories":                                            "list asset categories",
	"analytics.GetInventoryAPIV2AnalyticsCompositionKey":                                        "list asset composition",
	"analytics.GetInventoryAPIV2AnalyticsMetric":                                                "list asset metrics",
	"analytics.GetInventoryAPIV2AnalyticsMetricsList":                                           "",
	"analytics.GetInventoryAPIV2AnalyticsMetricsMetricID":                                       "get asset metric",
	"analytics.GetInventoryAPIV2AnalyticsSpendComposition":                                      "list spend composition",
	"analytics.GetInventoryAPIV2AnalyticsSpendMetric":                                           "list spend metrics",
	"analytics.GetInventoryAPIV2AnalyticsSpendTable":                                            "get spend table",
	"analytics.GetInventoryAPIV2AnalyticsSpendTrend":                                            "get spend trend",
	"analytics.GetInventoryAPIV2AnalyticsTable":                                                 "",
	"analytics.GetInventoryAPIV2AnalyticsTag":                                                   "list asset tags",
	"analytics.GetInventoryAPIV2AnalyticsTrend":                                                 "get asset trend",
	"benchmarks_assignment.DeleteComplianceAPIV1AssignmentsBenchmarkIDConnection":               "",
	"benchmarks_assignment.GetComplianceAPIV1AssignmentsBenchmarkBenchmarkID":                   "",
	"benchmarks_assignment.GetComplianceAPIV1AssignmentsConnectionConnectionID":                 "",
	"benchmarks_assignment.GetComplianceAPIV1AssignmentsResourceCollectionResourceCollectionID": "",
	"benchmarks_assignment.PostComplianceAPIV1AssignmentsBenchmarkIDConnection":                 "",
	"compliance.GetComplianceAPIV1BenchmarksBenchmarkIDPolicies":                                "",
	"compliance.GetComplianceAPIV1BenchmarksBenchmarkIDPoliciesPolicyID":                        "",
	"compliance.GetComplianceAPIV1BenchmarksBenchmarkIDSummary":                                 "",
	"compliance.GetComplianceAPIV1BenchmarksBenchmarkIDTrend":                                   "",
	"compliance.GetComplianceAPIV1BenchmarksSummary":                                            "",
	"compliance.GetComplianceAPIV1FindingsBenchmarkIDAccounts":                                  "",
	"compliance.GetComplianceAPIV1FindingsBenchmarkIDFieldCount":                                "",
	"compliance.GetComplianceAPIV1FindingsBenchmarkIDFieldTopCount":                             "",
	"compliance.GetComplianceAPIV1FindingsBenchmarkIDServices":                                  "",
	"compliance.GetComplianceAPIV1MetadataTagCompliance":                                        "",
	"compliance.GetComplianceAPIV1QueriesSync":                                                  "",
	"compliance.PostComplianceAPIV1AiPolicyPolicyIDRemediation":                                 "",
	"compliance.PostComplianceAPIV1Findings":                                                    "",
	"compliance.PostComplianceAPIV1FindingsFilters":                                             "",
	"connection_groups.GetOnboardAPIV1ConnectionGroups":                                         "",
	"connection_groups.GetOnboardAPIV1ConnectionGroupsConnectionGroupName":                      "",
	"connections.GetOnboardAPIV1ConnectionsSummary":                                             "list accounts summary",
	"cost_estimator.GetCostEstimatorAPIV1CostAws":                                               "",
	"cost_estimator.GetCostEstimatorAPIV1CostAzure":                                             "",
	"describe.PutScheduleAPIV1ComplianceTriggerBenchmarkID":                                     "",
	"describe.PutScheduleAPIV1DescribeConnectionStatus":                                         "get discovery status",
	"describe.PutScheduleAPIV1DescribeTriggerConnectionID":                                      "trigger discovery",
	"describe.PutScheduleAPIV1InsightTriggerInsightID":                                          "trigger insight",
	"insights.GetComplianceAPIV1Insight":                                                        "list insights",
	"insights.GetComplianceAPIV1InsightGroup":                                                   "list insight-groups",
	"insights.GetComplianceAPIV1InsightGroupInsightGroupID":                                     "get insight-group",
	"insights.GetComplianceAPIV1InsightGroupInsightGroupIDTrend":                                "get insight-group trend",
	"insights.GetComplianceAPIV1InsightInsightID":                                               "get insight",
	"insights.GetComplianceAPIV1InsightInsightIDTrend":                                          "get insight trend",
	"insights.GetComplianceAPIV1MetadataInsightInsightID":                                       "get insight metadata",
	"insights.GetComplianceAPIV1MetadataTagInsight":                                             "list insight tags",
	"keys.DeleteAuthAPIV1KeyIDDelete":                                                           "delete apikey",
	"keys.GetAuthAPIV1Keys":                                                                     "list apikeys",
	"keys.PostAuthAPIV1KeyCreate":                                                               "create apikey",
	"metadata.GetMetadataAPIV1Filter":                                                           "",
	"metadata.GetMetadataAPIV1MetadataKey":                                                      "",
	"metadata.PostMetadataAPIV1Filter":                                                          "",
	"metadata.PostMetadataAPIV1Metadata":                                                        "",
	"onboard.DeleteOnboardAPIV1CredentialCredentialID":                                          "delete credential",
	"onboard.DeleteOnboardAPIV1SourceSourceID":                                                  "delete account",
	"onboard.GetOnboardAPIV1CatalogMetrics":                                                     "",
	"onboard.GetOnboardAPIV1Connector":                                                          "list connectors",
	"onboard.GetOnboardAPIV1Credential":                                                         "list credentials",
	"onboard.GetOnboardAPIV1CredentialCredentialID":                                             "get credential",
	"onboard.GetOnboardAPIV1SourceSourceIDHealthcheck":                                          "get account healthcheck",
	"onboard.PostOnboardAPIV1ConnectionsAws":                                                    "onboard account aws",
	"onboard.PostOnboardAPIV1ConnectionsConnectionIDState":                                      "update account state",
	"onboard.PostOnboardAPIV1Credential":                                                        "onboard list-credentials",
	"onboard.PostOnboardAPIV1CredentialCredentialIDAutoonboard":                                 "run credential auto-onboard",
	"onboard.PostOnboardAPIV1SourceAws":                                                         "",
	"onboard.PostOnboardAPIV1SourceAzure":                                                       "onboard account azure",
	"onboard.PostOnboardAPIV2Credential":                                                        "onboard credential",
	"onboard.PutOnboardAPIV1CredentialCredentialID":                                             "update credential",
	"resource.PostAiAPIV1GptRun":                                                                "",
	"resource_collection.GetInventoryAPIV2MetadataResourceCollection":                           "list resource-collections metadata",
	"resource_collection.GetInventoryAPIV2MetadataResourceCollectionResourceCollectionID":       "get resource-collection metadata",
	"resource_collection.GetInventoryAPIV2ResourceCollection":                                   "list resource-collections",
	"resource_collection.GetInventoryAPIV2ResourceCollectionResourceCollectionID":               "get resource-collection",
	"resource_collection.GetInventoryAPIV2ResourceCollectionResourceCollectionIDLandscape":      "get resource-collection landscape",
	"scheduler.GetScheduleAPIV1Jobs":                                                            "list jobs",
	"smart_query.GetInventoryAPIV1Query":                                                        "list queries",
	"smart_query.GetInventoryAPIV1QueryRunHistory":                                              "get query history",
	"smart_query.PostInventoryAPIV1QueryRun":                                                    "run query",
	"stack.DeleteScheduleAPIV1StacksStackID":                                                    "",
	"stack.GetScheduleAPIV1Stacks":                                                              "",
	"stack.GetScheduleAPIV1StacksResource":                                                      "",
	"stack.GetScheduleAPIV1StacksStackID":                                                       "",
	"stack.GetScheduleAPIV1StacksStackIDInsight":                                                "",
	"stack.GetScheduleAPIV1StacksStackIDInsights":                                               "",
	"stack.PostScheduleAPIV1StacksCreate":                                                       "",
	"stack.PostScheduleAPIV1StacksStackIDFindings":                                              "",
	"users.DeleteAuthAPIV1UserRoleBinding":                                                      "revoke user access",
	"users.GetAuthAPIV1UserRoleBindings":                                                        "get user access",
	"users.GetAuthAPIV1UserUserID":                                                              "get user",
	"users.GetAuthAPIV1Users":                                                                   "list users",
	"users.GetAuthAPIV1WorkspaceRoleBindings":                                                   "get workspace users",
	"users.PostAuthAPIV1UserInvite":                                                             "invite user",
	"users.PutAuthAPIV1UserRoleBinding":                                                         "update user access",
	"workspace.DeleteWorkspaceAPIV1OrganizationOrganizationID":                                  "",
	"workspace.DeleteWorkspaceAPIV1WorkspaceWorkspaceID":                                        "delete workspace",
	"workspace.GetWorkspaceAPIV1BootstrapWorkspaceName":                                         "get workspace bootstrap-status",
	"workspace.GetWorkspaceAPIV1Organization":                                                   "",
	"workspace.GetWorkspaceAPIV1WorkspaceCurrent":                                               "",
	"workspace.GetWorkspaceAPIV1Workspaces":                                                     "list workspaces",
	"workspace.GetWorkspaceAPIV1WorkspacesByidWorkspaceID":                                      "",
	"workspace.GetWorkspaceAPIV1WorkspacesLimitsByidWorkspaceID":                                "",
	"workspace.GetWorkspaceAPIV1WorkspacesLimitsWorkspaceName":                                  "",
	"workspace.GetWorkspaceAPIV1WorkspacesWorkspaceID":                                          "",
	"workspace.PostWorkspaceAPIV1BootstrapWorkspaceNameCredential":                              "",
	"workspace.PostWorkspaceAPIV1BootstrapWorkspaceNameFinish":                                  "",
	"workspace.PostWorkspaceAPIV1Organization":                                                  "",
	"workspace.PostWorkspaceAPIV1Workspace":                                                     "create workspace",
	"workspace.PostWorkspaceAPIV1WorkspaceWorkspaceIDName":                                      "update workspace name",
	"workspace.PostWorkspaceAPIV1WorkspaceWorkspaceIDOrganization":                              "",
	"workspace.PostWorkspaceAPIV1WorkspaceWorkspaceIDOwner":                                     "update workspace owner",
	"workspace.PostWorkspaceAPIV1WorkspaceWorkspaceIDResume":                                    "resume workspace",
	"workspace.PostWorkspaceAPIV1WorkspaceWorkspaceIDSuspend":                                   "suspend workspace",
	"workspace.PostWorkspaceAPIV1WorkspaceWorkspaceIDTier":                                      "",
}

func GetCommandDef(api api.API) string {
	input := api.Client + "." + api.MethodName
	return commandDef[input]
}
