// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GithubComKaytuIoKaytuEnginePkgInventoryAPISpendTableRow github com kaytu io kaytu engine pkg inventory api spend table row
//
// swagger:model github_com_kaytu-io_kaytu-engine_pkg_inventory_api.SpendTableRow
type GithubComKaytuIoKaytuEnginePkgInventoryAPISpendTableRow struct {

	// account ID
	// Example: 1239042
	AccountID string `json:"accountID,omitempty"`

	// category
	// Example: Compute
	Category string `json:"category,omitempty"`

	// connector
	// Example: AWS
	Connector SourceType `json:"connector,omitempty"`

	// cost value
	CostValue map[string]float64 `json:"costValue,omitempty"`

	// dimension Id
	// Example: compute
	DimensionID string `json:"dimensionId,omitempty"`

	// dimension name
	// Example: Compute
	DimensionName string `json:"dimensionName,omitempty"`
}

// Validate validates this github com kaytu io kaytu engine pkg inventory api spend table row
func (m *GithubComKaytuIoKaytuEnginePkgInventoryAPISpendTableRow) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConnector(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComKaytuIoKaytuEnginePkgInventoryAPISpendTableRow) validateConnector(formats strfmt.Registry) error {
	if swag.IsZero(m.Connector) { // not required
		return nil
	}

	return nil
}

// ContextValidate validate this github com kaytu io kaytu engine pkg inventory api spend table row based on the context it is used
func (m *GithubComKaytuIoKaytuEnginePkgInventoryAPISpendTableRow) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateConnector(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComKaytuIoKaytuEnginePkgInventoryAPISpendTableRow) contextValidateConnector(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

// MarshalBinary interface implementation
func (m *GithubComKaytuIoKaytuEnginePkgInventoryAPISpendTableRow) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComKaytuIoKaytuEnginePkgInventoryAPISpendTableRow) UnmarshalBinary(b []byte) error {
	var res GithubComKaytuIoKaytuEnginePkgInventoryAPISpendTableRow
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
