// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GithubComKaytuIoKaytuEnginePkgOnboardAPIV2CreateCredentialV2Request github com kaytu io kaytu engine pkg onboard api v2 create credential v2 request
//
// swagger:model github_com_kaytu-io_kaytu-engine_pkg_onboard_api_v2.CreateCredentialV2Request
type GithubComKaytuIoKaytuEnginePkgOnboardAPIV2CreateCredentialV2Request struct {

	// aws config
	AwsConfig *GithubComKaytuIoKaytuEnginePkgOnboardAPIV2AWSCredentialV2Config `json:"awsConfig,omitempty"`

	// connector
	// Example: Azure
	Connector SourceType `json:"connector,omitempty"`
}

// Validate validates this github com kaytu io kaytu engine pkg onboard api v2 create credential v2 request
func (m *GithubComKaytuIoKaytuEnginePkgOnboardAPIV2CreateCredentialV2Request) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAwsConfig(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateConnector(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComKaytuIoKaytuEnginePkgOnboardAPIV2CreateCredentialV2Request) validateAwsConfig(formats strfmt.Registry) error {
	if swag.IsZero(m.AwsConfig) { // not required
		return nil
	}

	if m.AwsConfig != nil {
		if err := m.AwsConfig.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("awsConfig")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("awsConfig")
			}
			return err
		}
	}

	return nil
}

func (m *GithubComKaytuIoKaytuEnginePkgOnboardAPIV2CreateCredentialV2Request) validateConnector(formats strfmt.Registry) error {
	if swag.IsZero(m.Connector) { // not required
		return nil
	}

	return nil
}

// ContextValidate validate this github com kaytu io kaytu engine pkg onboard api v2 create credential v2 request based on the context it is used
func (m *GithubComKaytuIoKaytuEnginePkgOnboardAPIV2CreateCredentialV2Request) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAwsConfig(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateConnector(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComKaytuIoKaytuEnginePkgOnboardAPIV2CreateCredentialV2Request) contextValidateAwsConfig(ctx context.Context, formats strfmt.Registry) error {

	if m.AwsConfig != nil {

		if swag.IsZero(m.AwsConfig) { // not required
			return nil
		}

		if err := m.AwsConfig.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("awsConfig")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("awsConfig")
			}
			return err
		}
	}

	return nil
}

func (m *GithubComKaytuIoKaytuEnginePkgOnboardAPIV2CreateCredentialV2Request) contextValidateConnector(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

// MarshalBinary interface implementation
func (m *GithubComKaytuIoKaytuEnginePkgOnboardAPIV2CreateCredentialV2Request) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComKaytuIoKaytuEnginePkgOnboardAPIV2CreateCredentialV2Request) UnmarshalBinary(b []byte) error {
	var res GithubComKaytuIoKaytuEnginePkgOnboardAPIV2CreateCredentialV2Request
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
