// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// GithubComKaytuIoKaytuEnginePkgDescribeAPIJobStatus github com kaytu io kaytu engine pkg describe api job status
//
// swagger:model github_com_kaytu-io_kaytu-engine_pkg_describe_api.JobStatus
type GithubComKaytuIoKaytuEnginePkgDescribeAPIJobStatus string

func NewGithubComKaytuIoKaytuEnginePkgDescribeAPIJobStatus(value GithubComKaytuIoKaytuEnginePkgDescribeAPIJobStatus) *GithubComKaytuIoKaytuEnginePkgDescribeAPIJobStatus {
	return &value
}

// Pointer returns a pointer to a freshly-allocated GithubComKaytuIoKaytuEnginePkgDescribeAPIJobStatus.
func (m GithubComKaytuIoKaytuEnginePkgDescribeAPIJobStatus) Pointer() *GithubComKaytuIoKaytuEnginePkgDescribeAPIJobStatus {
	return &m
}

const (

	// GithubComKaytuIoKaytuEnginePkgDescribeAPIJobStatusCreated captures enum value "created"
	GithubComKaytuIoKaytuEnginePkgDescribeAPIJobStatusCreated GithubComKaytuIoKaytuEnginePkgDescribeAPIJobStatus = "created"

	// GithubComKaytuIoKaytuEnginePkgDescribeAPIJobStatusQueued captures enum value "queued"
	GithubComKaytuIoKaytuEnginePkgDescribeAPIJobStatusQueued GithubComKaytuIoKaytuEnginePkgDescribeAPIJobStatus = "queued"

	// GithubComKaytuIoKaytuEnginePkgDescribeAPIJobStatusInProgress captures enum value "in_progress"
	GithubComKaytuIoKaytuEnginePkgDescribeAPIJobStatusInProgress GithubComKaytuIoKaytuEnginePkgDescribeAPIJobStatus = "in_progress"

	// GithubComKaytuIoKaytuEnginePkgDescribeAPIJobStatusSuccessful captures enum value "successful"
	GithubComKaytuIoKaytuEnginePkgDescribeAPIJobStatusSuccessful GithubComKaytuIoKaytuEnginePkgDescribeAPIJobStatus = "successful"

	// GithubComKaytuIoKaytuEnginePkgDescribeAPIJobStatusFailure captures enum value "failure"
	GithubComKaytuIoKaytuEnginePkgDescribeAPIJobStatusFailure GithubComKaytuIoKaytuEnginePkgDescribeAPIJobStatus = "failure"

	// GithubComKaytuIoKaytuEnginePkgDescribeAPIJobStatusTimeout captures enum value "timeout"
	GithubComKaytuIoKaytuEnginePkgDescribeAPIJobStatusTimeout GithubComKaytuIoKaytuEnginePkgDescribeAPIJobStatus = "timeout"
)

// for schema
var githubComKaytuIoKaytuEnginePkgDescribeApiJobStatusEnum []interface{}

func init() {
	var res []GithubComKaytuIoKaytuEnginePkgDescribeAPIJobStatus
	if err := json.Unmarshal([]byte(`["created","queued","in_progress","successful","failure","timeout"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		githubComKaytuIoKaytuEnginePkgDescribeApiJobStatusEnum = append(githubComKaytuIoKaytuEnginePkgDescribeApiJobStatusEnum, v)
	}
}

func (m GithubComKaytuIoKaytuEnginePkgDescribeAPIJobStatus) validateGithubComKaytuIoKaytuEnginePkgDescribeAPIJobStatusEnum(path, location string, value GithubComKaytuIoKaytuEnginePkgDescribeAPIJobStatus) error {
	if err := validate.EnumCase(path, location, value, githubComKaytuIoKaytuEnginePkgDescribeApiJobStatusEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this github com kaytu io kaytu engine pkg describe api job status
func (m GithubComKaytuIoKaytuEnginePkgDescribeAPIJobStatus) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateGithubComKaytuIoKaytuEnginePkgDescribeAPIJobStatusEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this github com kaytu io kaytu engine pkg describe api job status based on context it is used
func (m GithubComKaytuIoKaytuEnginePkgDescribeAPIJobStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
