// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GithubComKaytuIoKaytuEnginePkgOnboardAPISourceConfigAWS github com kaytu io kaytu engine pkg onboard api source config a w s
//
// swagger:model github_com_kaytu-io_kaytu-engine_pkg_onboard_api.SourceConfigAWS
type GithubComKaytuIoKaytuEnginePkgOnboardAPISourceConfigAWS struct {

	// access key
	// Required: true
	AccessKey *string `json:"accessKey"`

	// account Id
	AccountID string `json:"accountId,omitempty"`

	// assume role name
	AssumeRoleName string `json:"assumeRoleName,omitempty"`

	// external Id
	ExternalID string `json:"externalId,omitempty"`

	// regions
	Regions []string `json:"regions"`

	// secret key
	// Required: true
	SecretKey *string `json:"secretKey"`
}

// Validate validates this github com kaytu io kaytu engine pkg onboard api source config a w s
func (m *GithubComKaytuIoKaytuEnginePkgOnboardAPISourceConfigAWS) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAccessKey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSecretKey(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComKaytuIoKaytuEnginePkgOnboardAPISourceConfigAWS) validateAccessKey(formats strfmt.Registry) error {

	if err := validate.Required("accessKey", "body", m.AccessKey); err != nil {
		return err
	}

	return nil
}

func (m *GithubComKaytuIoKaytuEnginePkgOnboardAPISourceConfigAWS) validateSecretKey(formats strfmt.Registry) error {

	if err := validate.Required("secretKey", "body", m.SecretKey); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this github com kaytu io kaytu engine pkg onboard api source config a w s based on context it is used
func (m *GithubComKaytuIoKaytuEnginePkgOnboardAPISourceConfigAWS) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GithubComKaytuIoKaytuEnginePkgOnboardAPISourceConfigAWS) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComKaytuIoKaytuEnginePkgOnboardAPISourceConfigAWS) UnmarshalBinary(b []byte) error {
	var res GithubComKaytuIoKaytuEnginePkgOnboardAPISourceConfigAWS
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
