// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// GithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatus github com kaytu io kaytu engine pkg describe api stack status
//
// swagger:model github_com_kaytu-io_kaytu-engine_pkg_describe_api.StackStatus
type GithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatus string

func NewGithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatus(value GithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatus) *GithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatus {
	return &value
}

// Pointer returns a pointer to a freshly-allocated GithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatus.
func (m GithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatus) Pointer() *GithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatus {
	return &m
}

const (

	// GithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatusPENDING captures enum value "PENDING"
	GithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatusPENDING GithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatus = "PENDING"

	// GithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatusSTALLED captures enum value "STALLED"
	GithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatusSTALLED GithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatus = "STALLED"

	// GithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatusCREATED captures enum value "CREATED"
	GithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatusCREATED GithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatus = "CREATED"

	// GithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatusDESCRIBING captures enum value "DESCRIBING"
	GithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatusDESCRIBING GithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatus = "DESCRIBING"

	// GithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatusDESCRIBEDRESOURCES captures enum value "DESCRIBED_RESOURCES"
	GithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatusDESCRIBEDRESOURCES GithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatus = "DESCRIBED_RESOURCES"

	// GithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatusEVALUATING captures enum value "EVALUATING"
	GithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatusEVALUATING GithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatus = "EVALUATING"

	// GithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatusFAILED captures enum value "FAILED"
	GithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatusFAILED GithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatus = "FAILED"

	// GithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatusCOMPLETED captures enum value "COMPLETED"
	GithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatusCOMPLETED GithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatus = "COMPLETED"

	// GithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatusCOMPLETEDWITHFAILURE captures enum value "COMPLETED_WITH_FAILURE"
	GithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatusCOMPLETEDWITHFAILURE GithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatus = "COMPLETED_WITH_FAILURE"
)

// for schema
var githubComKaytuIoKaytuEnginePkgDescribeApiStackStatusEnum []interface{}

func init() {
	var res []GithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatus
	if err := json.Unmarshal([]byte(`["PENDING","STALLED","CREATED","DESCRIBING","DESCRIBED_RESOURCES","EVALUATING","FAILED","COMPLETED","COMPLETED_WITH_FAILURE"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		githubComKaytuIoKaytuEnginePkgDescribeApiStackStatusEnum = append(githubComKaytuIoKaytuEnginePkgDescribeApiStackStatusEnum, v)
	}
}

func (m GithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatus) validateGithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatusEnum(path, location string, value GithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatus) error {
	if err := validate.EnumCase(path, location, value, githubComKaytuIoKaytuEnginePkgDescribeApiStackStatusEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this github com kaytu io kaytu engine pkg describe api stack status
func (m GithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatus) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateGithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatusEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this github com kaytu io kaytu engine pkg describe api stack status based on context it is used
func (m GithubComKaytuIoKaytuEnginePkgDescribeAPIStackStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
