// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GithubComKaytuIoKaytuEnginePkgWorkspaceAPIWorkspaceLimitsUsage github com kaytu io kaytu engine pkg workspace api workspace limits usage
//
// swagger:model github_com_kaytu-io_kaytu-engine_pkg_workspace_api.WorkspaceLimitsUsage
type GithubComKaytuIoKaytuEnginePkgWorkspaceAPIWorkspaceLimitsUsage struct {

	// current connections
	// Example: 100
	CurrentConnections int64 `json:"currentConnections,omitempty"`

	// current resources
	// Example: 10000
	CurrentResources int64 `json:"currentResources,omitempty"`

	// current users
	// Example: 10
	CurrentUsers int64 `json:"currentUsers,omitempty"`

	// id
	// Example: ws-698542025141040315
	ID string `json:"id,omitempty"`

	// max connections
	// Example: 1000
	MaxConnections int64 `json:"maxConnections,omitempty"`

	// max resources
	// Example: 100000
	MaxResources int64 `json:"maxResources,omitempty"`

	// max users
	// Example: 100
	MaxUsers int64 `json:"maxUsers,omitempty"`

	// name
	// Example: keibi
	Name string `json:"name,omitempty"`
}

// Validate validates this github com kaytu io kaytu engine pkg workspace api workspace limits usage
func (m *GithubComKaytuIoKaytuEnginePkgWorkspaceAPIWorkspaceLimitsUsage) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this github com kaytu io kaytu engine pkg workspace api workspace limits usage based on context it is used
func (m *GithubComKaytuIoKaytuEnginePkgWorkspaceAPIWorkspaceLimitsUsage) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GithubComKaytuIoKaytuEnginePkgWorkspaceAPIWorkspaceLimitsUsage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComKaytuIoKaytuEnginePkgWorkspaceAPIWorkspaceLimitsUsage) UnmarshalBinary(b []byte) error {
	var res GithubComKaytuIoKaytuEnginePkgWorkspaceAPIWorkspaceLimitsUsage
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
