// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// GithubComKaytuIoKaytuEnginePkgInventoryAPISortFieldType github com kaytu io kaytu engine pkg inventory api sort field type
//
// swagger:model github_com_kaytu-io_kaytu-engine_pkg_inventory_api.SortFieldType
type GithubComKaytuIoKaytuEnginePkgInventoryAPISortFieldType string

func NewGithubComKaytuIoKaytuEnginePkgInventoryAPISortFieldType(value GithubComKaytuIoKaytuEnginePkgInventoryAPISortFieldType) *GithubComKaytuIoKaytuEnginePkgInventoryAPISortFieldType {
	return &value
}

// Pointer returns a pointer to a freshly-allocated GithubComKaytuIoKaytuEnginePkgInventoryAPISortFieldType.
func (m GithubComKaytuIoKaytuEnginePkgInventoryAPISortFieldType) Pointer() *GithubComKaytuIoKaytuEnginePkgInventoryAPISortFieldType {
	return &m
}

const (

	// GithubComKaytuIoKaytuEnginePkgInventoryAPISortFieldTypeResourceID captures enum value "resourceID"
	GithubComKaytuIoKaytuEnginePkgInventoryAPISortFieldTypeResourceID GithubComKaytuIoKaytuEnginePkgInventoryAPISortFieldType = "resourceID"

	// GithubComKaytuIoKaytuEnginePkgInventoryAPISortFieldTypeResourceName captures enum value "resourceName"
	GithubComKaytuIoKaytuEnginePkgInventoryAPISortFieldTypeResourceName GithubComKaytuIoKaytuEnginePkgInventoryAPISortFieldType = "resourceName"

	// GithubComKaytuIoKaytuEnginePkgInventoryAPISortFieldTypeProvider captures enum value "provider"
	GithubComKaytuIoKaytuEnginePkgInventoryAPISortFieldTypeProvider GithubComKaytuIoKaytuEnginePkgInventoryAPISortFieldType = "provider"

	// GithubComKaytuIoKaytuEnginePkgInventoryAPISortFieldTypeResourceType captures enum value "resourceType"
	GithubComKaytuIoKaytuEnginePkgInventoryAPISortFieldTypeResourceType GithubComKaytuIoKaytuEnginePkgInventoryAPISortFieldType = "resourceType"

	// GithubComKaytuIoKaytuEnginePkgInventoryAPISortFieldTypeResourceGroup captures enum value "resourceGroup"
	GithubComKaytuIoKaytuEnginePkgInventoryAPISortFieldTypeResourceGroup GithubComKaytuIoKaytuEnginePkgInventoryAPISortFieldType = "resourceGroup"

	// GithubComKaytuIoKaytuEnginePkgInventoryAPISortFieldTypeLocation captures enum value "location"
	GithubComKaytuIoKaytuEnginePkgInventoryAPISortFieldTypeLocation GithubComKaytuIoKaytuEnginePkgInventoryAPISortFieldType = "location"

	// GithubComKaytuIoKaytuEnginePkgInventoryAPISortFieldTypeConnectionID captures enum value "connectionID"
	GithubComKaytuIoKaytuEnginePkgInventoryAPISortFieldTypeConnectionID GithubComKaytuIoKaytuEnginePkgInventoryAPISortFieldType = "connectionID"
)

// for schema
var githubComKaytuIoKaytuEnginePkgInventoryApiSortFieldTypeEnum []interface{}

func init() {
	var res []GithubComKaytuIoKaytuEnginePkgInventoryAPISortFieldType
	if err := json.Unmarshal([]byte(`["resourceID","resourceName","provider","resourceType","resourceGroup","location","connectionID"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		githubComKaytuIoKaytuEnginePkgInventoryApiSortFieldTypeEnum = append(githubComKaytuIoKaytuEnginePkgInventoryApiSortFieldTypeEnum, v)
	}
}

func (m GithubComKaytuIoKaytuEnginePkgInventoryAPISortFieldType) validateGithubComKaytuIoKaytuEnginePkgInventoryAPISortFieldTypeEnum(path, location string, value GithubComKaytuIoKaytuEnginePkgInventoryAPISortFieldType) error {
	if err := validate.EnumCase(path, location, value, githubComKaytuIoKaytuEnginePkgInventoryApiSortFieldTypeEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this github com kaytu io kaytu engine pkg inventory api sort field type
func (m GithubComKaytuIoKaytuEnginePkgInventoryAPISortFieldType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateGithubComKaytuIoKaytuEnginePkgInventoryAPISortFieldTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this github com kaytu io kaytu engine pkg inventory api sort field type based on context it is used
func (m GithubComKaytuIoKaytuEnginePkgInventoryAPISortFieldType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
