// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// GithubComKaytuIoKaytuEnginePkgDescribeAPIJobType github com kaytu io kaytu engine pkg describe api job type
//
// swagger:model github_com_kaytu-io_kaytu-engine_pkg_describe_api.JobType
type GithubComKaytuIoKaytuEnginePkgDescribeAPIJobType string

func NewGithubComKaytuIoKaytuEnginePkgDescribeAPIJobType(value GithubComKaytuIoKaytuEnginePkgDescribeAPIJobType) *GithubComKaytuIoKaytuEnginePkgDescribeAPIJobType {
	return &value
}

// Pointer returns a pointer to a freshly-allocated GithubComKaytuIoKaytuEnginePkgDescribeAPIJobType.
func (m GithubComKaytuIoKaytuEnginePkgDescribeAPIJobType) Pointer() *GithubComKaytuIoKaytuEnginePkgDescribeAPIJobType {
	return &m
}

const (

	// GithubComKaytuIoKaytuEnginePkgDescribeAPIJobTypeDiscovery captures enum value "discovery"
	GithubComKaytuIoKaytuEnginePkgDescribeAPIJobTypeDiscovery GithubComKaytuIoKaytuEnginePkgDescribeAPIJobType = "discovery"

	// GithubComKaytuIoKaytuEnginePkgDescribeAPIJobTypeAnalytics captures enum value "analytics"
	GithubComKaytuIoKaytuEnginePkgDescribeAPIJobTypeAnalytics GithubComKaytuIoKaytuEnginePkgDescribeAPIJobType = "analytics"

	// GithubComKaytuIoKaytuEnginePkgDescribeAPIJobTypeCompliance captures enum value "compliance"
	GithubComKaytuIoKaytuEnginePkgDescribeAPIJobTypeCompliance GithubComKaytuIoKaytuEnginePkgDescribeAPIJobType = "compliance"

	// GithubComKaytuIoKaytuEnginePkgDescribeAPIJobTypeInsight captures enum value "insight"
	GithubComKaytuIoKaytuEnginePkgDescribeAPIJobTypeInsight GithubComKaytuIoKaytuEnginePkgDescribeAPIJobType = "insight"
)

// for schema
var githubComKaytuIoKaytuEnginePkgDescribeApiJobTypeEnum []interface{}

func init() {
	var res []GithubComKaytuIoKaytuEnginePkgDescribeAPIJobType
	if err := json.Unmarshal([]byte(`["discovery","analytics","compliance","insight"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		githubComKaytuIoKaytuEnginePkgDescribeApiJobTypeEnum = append(githubComKaytuIoKaytuEnginePkgDescribeApiJobTypeEnum, v)
	}
}

func (m GithubComKaytuIoKaytuEnginePkgDescribeAPIJobType) validateGithubComKaytuIoKaytuEnginePkgDescribeAPIJobTypeEnum(path, location string, value GithubComKaytuIoKaytuEnginePkgDescribeAPIJobType) error {
	if err := validate.EnumCase(path, location, value, githubComKaytuIoKaytuEnginePkgDescribeApiJobTypeEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this github com kaytu io kaytu engine pkg describe api job type
func (m GithubComKaytuIoKaytuEnginePkgDescribeAPIJobType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateGithubComKaytuIoKaytuEnginePkgDescribeAPIJobTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this github com kaytu io kaytu engine pkg describe api job type based on context it is used
func (m GithubComKaytuIoKaytuEnginePkgDescribeAPIJobType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
