// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GithubComKaytuIoKaytuEnginePkgComplianceAPIPolicySummary github com kaytu io kaytu engine pkg compliance api policy summary
//
// swagger:model github_com_kaytu-io_kaytu-engine_pkg_compliance_api.PolicySummary
type GithubComKaytuIoKaytuEnginePkgComplianceAPIPolicySummary struct {

	// evaluated at
	EvaluatedAt int64 `json:"evaluatedAt,omitempty"`

	// failed connection count
	FailedConnectionCount int64 `json:"failedConnectionCount,omitempty"`

	// failed resources count
	FailedResourcesCount int64 `json:"failedResourcesCount,omitempty"`

	// passed
	Passed bool `json:"passed,omitempty"`

	// policy
	Policy *GithubComKaytuIoKaytuEnginePkgComplianceAPIPolicy `json:"policy,omitempty"`

	// total connection count
	TotalConnectionCount int64 `json:"totalConnectionCount,omitempty"`

	// total resources count
	TotalResourcesCount int64 `json:"totalResourcesCount,omitempty"`
}

// Validate validates this github com kaytu io kaytu engine pkg compliance api policy summary
func (m *GithubComKaytuIoKaytuEnginePkgComplianceAPIPolicySummary) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePolicy(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComKaytuIoKaytuEnginePkgComplianceAPIPolicySummary) validatePolicy(formats strfmt.Registry) error {
	if swag.IsZero(m.Policy) { // not required
		return nil
	}

	if m.Policy != nil {
		if err := m.Policy.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("policy")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("policy")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this github com kaytu io kaytu engine pkg compliance api policy summary based on the context it is used
func (m *GithubComKaytuIoKaytuEnginePkgComplianceAPIPolicySummary) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePolicy(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComKaytuIoKaytuEnginePkgComplianceAPIPolicySummary) contextValidatePolicy(ctx context.Context, formats strfmt.Registry) error {

	if m.Policy != nil {

		if swag.IsZero(m.Policy) { // not required
			return nil
		}

		if err := m.Policy.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("policy")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("policy")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *GithubComKaytuIoKaytuEnginePkgComplianceAPIPolicySummary) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComKaytuIoKaytuEnginePkgComplianceAPIPolicySummary) UnmarshalBinary(b []byte) error {
	var res GithubComKaytuIoKaytuEnginePkgComplianceAPIPolicySummary
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
