// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GithubComKaytuIoKaytuEnginePkgInventoryAPIRunQueryResponse github com kaytu io kaytu engine pkg inventory api run query response
//
// swagger:model github_com_kaytu-io_kaytu-engine_pkg_inventory_api.RunQueryResponse
type GithubComKaytuIoKaytuEnginePkgInventoryAPIRunQueryResponse struct {

	// Column names
	Headers []string `json:"headers"`

	// Query
	Query string `json:"query,omitempty"`

	// Result of query. in order to access a specific cell please use Result[Row][Column]
	Result [][]interface{} `json:"result"`

	// Query Title
	Title string `json:"title,omitempty"`
}

// Validate validates this github com kaytu io kaytu engine pkg inventory api run query response
func (m *GithubComKaytuIoKaytuEnginePkgInventoryAPIRunQueryResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this github com kaytu io kaytu engine pkg inventory api run query response based on context it is used
func (m *GithubComKaytuIoKaytuEnginePkgInventoryAPIRunQueryResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GithubComKaytuIoKaytuEnginePkgInventoryAPIRunQueryResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComKaytuIoKaytuEnginePkgInventoryAPIRunQueryResponse) UnmarshalBinary(b []byte) error {
	var res GithubComKaytuIoKaytuEnginePkgInventoryAPIRunQueryResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
