// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GithubComKaytuIoKaytuEnginePkgComplianceAPIFinding github com kaytu io kaytu engine pkg compliance api finding
//
// swagger:model github_com_kaytu-io_kaytu-engine_pkg_compliance_api.Finding
type GithubComKaytuIoKaytuEnginePkgComplianceAPIFinding struct {

	// benchmark ID
	// Example: azure_cis_v140
	BenchmarkID string `json:"benchmarkID,omitempty"`

	// compliance job ID
	// Example: 1
	ComplianceJobID int64 `json:"complianceJobID,omitempty"`

	// connection ID
	// Example: 8e0f8e7a-1b1c-4e6f-b7e4-9c6af9d2b1c8
	ConnectionID string `json:"connectionID,omitempty"`

	// connector
	// Example: Azure
	Connector SourceType `json:"connector,omitempty"`

	// control ID
	// Example: azure_cis_v140_7_5
	ControlID string `json:"controlID,omitempty"`

	// control title
	ControlTitle string `json:"controlTitle,omitempty"`

	// evaluated at
	// Example: 1589395200
	EvaluatedAt int64 `json:"evaluatedAt,omitempty"`

	// evaluator
	// Example: steampipe-v0.5
	Evaluator string `json:"evaluator,omitempty"`

	// kaytu resource ID
	// Example: /subscriptions/123/resourceGroups/rg-1/providers/Microsoft.Compute/virtualMachines/vm-1
	KaytuResourceID string `json:"kaytuResourceID,omitempty"`

	// no of occurrences
	// Example: 1
	NoOfOccurrences int64 `json:"noOfOccurrences,omitempty"`

	// parent benchmark names
	// Example: ["Azure CIS v1.4.0"]
	ParentBenchmarkNames []string `json:"parentBenchmarkNames"`

	// parent benchmarks
	ParentBenchmarks []string `json:"parentBenchmarks"`

	// parent compliance job ID
	// Example: 1
	ParentComplianceJobID int64 `json:"parentComplianceJobID,omitempty"`

	// Connection ID
	// Example: 8e0f8e7a-1b1c-4e6f-b7e4-9c6af9d2b1c8
	ProviderConnectionID string `json:"providerConnectionID,omitempty"`

	// Connection ID
	// Example: 8e0f8e7a-1b1c-4e6f-b7e4-9c6af9d2b1c8
	ProviderConnectionName string `json:"providerConnectionName,omitempty"`

	// reason
	// Example: The VM is not using managed disks
	Reason string `json:"reason,omitempty"`

	// Resource collection
	ResourceCollection string `json:"resourceCollection,omitempty"`

	// resource ID
	// Example: /subscriptions/123/resourceGroups/rg-1/providers/Microsoft.Compute/virtualMachines/vm-1
	ResourceID string `json:"resourceID,omitempty"`

	// resource location
	// Example: eastus
	ResourceLocation string `json:"resourceLocation,omitempty"`

	// resource name
	// Example: vm-1
	ResourceName string `json:"resourceName,omitempty"`

	// resource type
	// Example: Microsoft.Compute/virtualMachines
	ResourceType string `json:"resourceType,omitempty"`

	// resource type name
	// Example: Virtual Machine
	ResourceTypeName string `json:"resourceTypeName,omitempty"`

	// result
	// Example: alarm
	Result TypesComplianceResult `json:"result,omitempty"`

	// severity
	// Example: low
	Severity TypesFindingSeverity `json:"severity,omitempty"`

	// sort key
	SortKey []interface{} `json:"sortKey"`

	// state active
	// Example: true
	StateActive bool `json:"stateActive,omitempty"`
}

// Validate validates this github com kaytu io kaytu engine pkg compliance api finding
func (m *GithubComKaytuIoKaytuEnginePkgComplianceAPIFinding) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConnector(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSeverity(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComKaytuIoKaytuEnginePkgComplianceAPIFinding) validateConnector(formats strfmt.Registry) error {
	if swag.IsZero(m.Connector) { // not required
		return nil
	}

	return nil
}

func (m *GithubComKaytuIoKaytuEnginePkgComplianceAPIFinding) validateResult(formats strfmt.Registry) error {
	if swag.IsZero(m.Result) { // not required
		return nil
	}

	return nil
}

func (m *GithubComKaytuIoKaytuEnginePkgComplianceAPIFinding) validateSeverity(formats strfmt.Registry) error {
	if swag.IsZero(m.Severity) { // not required
		return nil
	}

	return nil
}

// ContextValidate validate this github com kaytu io kaytu engine pkg compliance api finding based on the context it is used
func (m *GithubComKaytuIoKaytuEnginePkgComplianceAPIFinding) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateConnector(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateResult(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSeverity(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GithubComKaytuIoKaytuEnginePkgComplianceAPIFinding) contextValidateConnector(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

func (m *GithubComKaytuIoKaytuEnginePkgComplianceAPIFinding) contextValidateResult(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

func (m *GithubComKaytuIoKaytuEnginePkgComplianceAPIFinding) contextValidateSeverity(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

// MarshalBinary interface implementation
func (m *GithubComKaytuIoKaytuEnginePkgComplianceAPIFinding) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComKaytuIoKaytuEnginePkgComplianceAPIFinding) UnmarshalBinary(b []byte) error {
	var res GithubComKaytuIoKaytuEnginePkgComplianceAPIFinding
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
