// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GitlabComKeibiengineKeibiEnginePkgWorkspaceAPIOrganizationResponse gitlab com keibiengine keibi engine pkg workspace api organization response
//
// swagger:model gitlab_com_keibiengine_keibi-engine_pkg_workspace_api.OrganizationResponse
type GitlabComKeibiengineKeibiEnginePkgWorkspaceAPIOrganizationResponse struct {

	// address line1
	AddressLine1 string `json:"addressLine1,omitempty"`

	// address line2
	AddressLine2 string `json:"addressLine2,omitempty"`

	// address line3
	AddressLine3 string `json:"addressLine3,omitempty"`

	// city
	City string `json:"city,omitempty"`

	// company name
	CompanyName string `json:"companyName,omitempty"`

	// contact email
	ContactEmail string `json:"contactEmail,omitempty"`

	// contact person
	ContactPerson string `json:"contactPerson,omitempty"`

	// contact phone
	ContactPhone string `json:"contactPhone,omitempty"`

	// country
	Country string `json:"country,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// state
	State string `json:"state,omitempty"`

	// url
	URL string `json:"url,omitempty"`
}

// Validate validates this gitlab com keibiengine keibi engine pkg workspace api organization response
func (m *GitlabComKeibiengineKeibiEnginePkgWorkspaceAPIOrganizationResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this gitlab com keibiengine keibi engine pkg workspace api organization response based on context it is used
func (m *GitlabComKeibiengineKeibiEnginePkgWorkspaceAPIOrganizationResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GitlabComKeibiengineKeibiEnginePkgWorkspaceAPIOrganizationResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GitlabComKeibiengineKeibiEnginePkgWorkspaceAPIOrganizationResponse) UnmarshalBinary(b []byte) error {
	var res GitlabComKeibiengineKeibiEnginePkgWorkspaceAPIOrganizationResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
