// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GitlabComKeibiengineKeibiEnginePkgDescribeAPIEvaluateStack gitlab com keibiengine keibi engine pkg describe api evaluate stack
//
// swagger:model gitlab_com_keibiengine_keibi-engine_pkg_describe_api.EvaluateStack
type GitlabComKeibiengineKeibiEnginePkgDescribeAPIEvaluateStack struct {

	// benchmarks
	// Required: true
	Benchmarks []string `json:"benchmarks"`

	// stack Id
	StackID string `json:"stackId,omitempty"`
}

// Validate validates this gitlab com keibiengine keibi engine pkg describe api evaluate stack
func (m *GitlabComKeibiengineKeibiEnginePkgDescribeAPIEvaluateStack) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBenchmarks(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GitlabComKeibiengineKeibiEnginePkgDescribeAPIEvaluateStack) validateBenchmarks(formats strfmt.Registry) error {

	if err := validate.Required("benchmarks", "body", m.Benchmarks); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this gitlab com keibiengine keibi engine pkg describe api evaluate stack based on context it is used
func (m *GitlabComKeibiengineKeibiEnginePkgDescribeAPIEvaluateStack) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GitlabComKeibiengineKeibiEnginePkgDescribeAPIEvaluateStack) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GitlabComKeibiengineKeibiEnginePkgDescribeAPIEvaluateStack) UnmarshalBinary(b []byte) error {
	var res GitlabComKeibiengineKeibiEnginePkgDescribeAPIEvaluateStack
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
