// Code generated by go-swagger; DO NOT EDIT.

package inventory

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetInventoryAPIV2ResourcesTrendParams creates a new GetInventoryAPIV2ResourcesTrendParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetInventoryAPIV2ResourcesTrendParams() *GetInventoryAPIV2ResourcesTrendParams {
	return &GetInventoryAPIV2ResourcesTrendParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetInventoryAPIV2ResourcesTrendParamsWithTimeout creates a new GetInventoryAPIV2ResourcesTrendParams object
// with the ability to set a timeout on a request.
func NewGetInventoryAPIV2ResourcesTrendParamsWithTimeout(timeout time.Duration) *GetInventoryAPIV2ResourcesTrendParams {
	return &GetInventoryAPIV2ResourcesTrendParams{
		timeout: timeout,
	}
}

// NewGetInventoryAPIV2ResourcesTrendParamsWithContext creates a new GetInventoryAPIV2ResourcesTrendParams object
// with the ability to set a context for a request.
func NewGetInventoryAPIV2ResourcesTrendParamsWithContext(ctx context.Context) *GetInventoryAPIV2ResourcesTrendParams {
	return &GetInventoryAPIV2ResourcesTrendParams{
		Context: ctx,
	}
}

// NewGetInventoryAPIV2ResourcesTrendParamsWithHTTPClient creates a new GetInventoryAPIV2ResourcesTrendParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetInventoryAPIV2ResourcesTrendParamsWithHTTPClient(client *http.Client) *GetInventoryAPIV2ResourcesTrendParams {
	return &GetInventoryAPIV2ResourcesTrendParams{
		HTTPClient: client,
	}
}

/*
GetInventoryAPIV2ResourcesTrendParams contains all the parameters to send to the API endpoint

	for the get inventory API v2 resources trend operation.

	Typically these are written to a http.Request.
*/
type GetInventoryAPIV2ResourcesTrendParams struct {

	/* ConnectionID.

	   Connection IDs to filter by
	*/
	ConnectionID []string

	/* Connector.

	   Connector type to filter by
	*/
	Connector []string

	/* DatapointCount.

	   maximum number of datapoints to return, default is 30
	*/
	DatapointCount *string

	/* EndTime.

	   timestamp for end in epoch seconds
	*/
	EndTime *string

	/* Servicename.

	   Service names to filter by
	*/
	Servicename []string

	/* StartTime.

	   timestamp for start in epoch seconds
	*/
	StartTime *string

	/* Tag.

	   Key-Value tags in key=value format to filter by
	*/
	Tag []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get inventory API v2 resources trend params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInventoryAPIV2ResourcesTrendParams) WithDefaults() *GetInventoryAPIV2ResourcesTrendParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get inventory API v2 resources trend params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInventoryAPIV2ResourcesTrendParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get inventory API v2 resources trend params
func (o *GetInventoryAPIV2ResourcesTrendParams) WithTimeout(timeout time.Duration) *GetInventoryAPIV2ResourcesTrendParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get inventory API v2 resources trend params
func (o *GetInventoryAPIV2ResourcesTrendParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get inventory API v2 resources trend params
func (o *GetInventoryAPIV2ResourcesTrendParams) WithContext(ctx context.Context) *GetInventoryAPIV2ResourcesTrendParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get inventory API v2 resources trend params
func (o *GetInventoryAPIV2ResourcesTrendParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get inventory API v2 resources trend params
func (o *GetInventoryAPIV2ResourcesTrendParams) WithHTTPClient(client *http.Client) *GetInventoryAPIV2ResourcesTrendParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get inventory API v2 resources trend params
func (o *GetInventoryAPIV2ResourcesTrendParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithConnectionID adds the connectionID to the get inventory API v2 resources trend params
func (o *GetInventoryAPIV2ResourcesTrendParams) WithConnectionID(connectionID []string) *GetInventoryAPIV2ResourcesTrendParams {
	o.SetConnectionID(connectionID)
	return o
}

// SetConnectionID adds the connectionId to the get inventory API v2 resources trend params
func (o *GetInventoryAPIV2ResourcesTrendParams) SetConnectionID(connectionID []string) {
	o.ConnectionID = connectionID
}

// WithConnector adds the connector to the get inventory API v2 resources trend params
func (o *GetInventoryAPIV2ResourcesTrendParams) WithConnector(connector []string) *GetInventoryAPIV2ResourcesTrendParams {
	o.SetConnector(connector)
	return o
}

// SetConnector adds the connector to the get inventory API v2 resources trend params
func (o *GetInventoryAPIV2ResourcesTrendParams) SetConnector(connector []string) {
	o.Connector = connector
}

// WithDatapointCount adds the datapointCount to the get inventory API v2 resources trend params
func (o *GetInventoryAPIV2ResourcesTrendParams) WithDatapointCount(datapointCount *string) *GetInventoryAPIV2ResourcesTrendParams {
	o.SetDatapointCount(datapointCount)
	return o
}

// SetDatapointCount adds the datapointCount to the get inventory API v2 resources trend params
func (o *GetInventoryAPIV2ResourcesTrendParams) SetDatapointCount(datapointCount *string) {
	o.DatapointCount = datapointCount
}

// WithEndTime adds the endTime to the get inventory API v2 resources trend params
func (o *GetInventoryAPIV2ResourcesTrendParams) WithEndTime(endTime *string) *GetInventoryAPIV2ResourcesTrendParams {
	o.SetEndTime(endTime)
	return o
}

// SetEndTime adds the endTime to the get inventory API v2 resources trend params
func (o *GetInventoryAPIV2ResourcesTrendParams) SetEndTime(endTime *string) {
	o.EndTime = endTime
}

// WithServicename adds the servicename to the get inventory API v2 resources trend params
func (o *GetInventoryAPIV2ResourcesTrendParams) WithServicename(servicename []string) *GetInventoryAPIV2ResourcesTrendParams {
	o.SetServicename(servicename)
	return o
}

// SetServicename adds the servicename to the get inventory API v2 resources trend params
func (o *GetInventoryAPIV2ResourcesTrendParams) SetServicename(servicename []string) {
	o.Servicename = servicename
}

// WithStartTime adds the startTime to the get inventory API v2 resources trend params
func (o *GetInventoryAPIV2ResourcesTrendParams) WithStartTime(startTime *string) *GetInventoryAPIV2ResourcesTrendParams {
	o.SetStartTime(startTime)
	return o
}

// SetStartTime adds the startTime to the get inventory API v2 resources trend params
func (o *GetInventoryAPIV2ResourcesTrendParams) SetStartTime(startTime *string) {
	o.StartTime = startTime
}

// WithTag adds the tag to the get inventory API v2 resources trend params
func (o *GetInventoryAPIV2ResourcesTrendParams) WithTag(tag []string) *GetInventoryAPIV2ResourcesTrendParams {
	o.SetTag(tag)
	return o
}

// SetTag adds the tag to the get inventory API v2 resources trend params
func (o *GetInventoryAPIV2ResourcesTrendParams) SetTag(tag []string) {
	o.Tag = tag
}

// WriteToRequest writes these params to a swagger request
func (o *GetInventoryAPIV2ResourcesTrendParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ConnectionID != nil {

		// binding items for connectionId
		joinedConnectionID := o.bindParamConnectionID(reg)

		// query array param connectionId
		if err := r.SetQueryParam("connectionId", joinedConnectionID...); err != nil {
			return err
		}
	}

	if o.Connector != nil {

		// binding items for connector
		joinedConnector := o.bindParamConnector(reg)

		// query array param connector
		if err := r.SetQueryParam("connector", joinedConnector...); err != nil {
			return err
		}
	}

	if o.DatapointCount != nil {

		// query param datapointCount
		var qrDatapointCount string

		if o.DatapointCount != nil {
			qrDatapointCount = *o.DatapointCount
		}
		qDatapointCount := qrDatapointCount
		if qDatapointCount != "" {

			if err := r.SetQueryParam("datapointCount", qDatapointCount); err != nil {
				return err
			}
		}
	}

	if o.EndTime != nil {

		// query param endTime
		var qrEndTime string

		if o.EndTime != nil {
			qrEndTime = *o.EndTime
		}
		qEndTime := qrEndTime
		if qEndTime != "" {

			if err := r.SetQueryParam("endTime", qEndTime); err != nil {
				return err
			}
		}
	}

	if o.Servicename != nil {

		// binding items for servicename
		joinedServicename := o.bindParamServicename(reg)

		// query array param servicename
		if err := r.SetQueryParam("servicename", joinedServicename...); err != nil {
			return err
		}
	}

	if o.StartTime != nil {

		// query param startTime
		var qrStartTime string

		if o.StartTime != nil {
			qrStartTime = *o.StartTime
		}
		qStartTime := qrStartTime
		if qStartTime != "" {

			if err := r.SetQueryParam("startTime", qStartTime); err != nil {
				return err
			}
		}
	}

	if o.Tag != nil {

		// binding items for tag
		joinedTag := o.bindParamTag(reg)

		// query array param tag
		if err := r.SetQueryParam("tag", joinedTag...); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamGetInventoryAPIV2ResourcesTrend binds the parameter connectionId
func (o *GetInventoryAPIV2ResourcesTrendParams) bindParamConnectionID(formats strfmt.Registry) []string {
	connectionIDIR := o.ConnectionID

	var connectionIDIC []string
	for _, connectionIDIIR := range connectionIDIR { // explode []string

		connectionIDIIV := connectionIDIIR // string as string
		connectionIDIC = append(connectionIDIC, connectionIDIIV)
	}

	// items.CollectionFormat: "csv"
	connectionIDIS := swag.JoinByFormat(connectionIDIC, "csv")

	return connectionIDIS
}

// bindParamGetInventoryAPIV2ResourcesTrend binds the parameter connector
func (o *GetInventoryAPIV2ResourcesTrendParams) bindParamConnector(formats strfmt.Registry) []string {
	connectorIR := o.Connector

	var connectorIC []string
	for _, connectorIIR := range connectorIR { // explode []string

		connectorIIV := connectorIIR // string as string
		connectorIC = append(connectorIC, connectorIIV)
	}

	// items.CollectionFormat: "csv"
	connectorIS := swag.JoinByFormat(connectorIC, "csv")

	return connectorIS
}

// bindParamGetInventoryAPIV2ResourcesTrend binds the parameter servicename
func (o *GetInventoryAPIV2ResourcesTrendParams) bindParamServicename(formats strfmt.Registry) []string {
	servicenameIR := o.Servicename

	var servicenameIC []string
	for _, servicenameIIR := range servicenameIR { // explode []string

		servicenameIIV := servicenameIIR // string as string
		servicenameIC = append(servicenameIC, servicenameIIV)
	}

	// items.CollectionFormat: "csv"
	servicenameIS := swag.JoinByFormat(servicenameIC, "csv")

	return servicenameIS
}

// bindParamGetInventoryAPIV2ResourcesTrend binds the parameter tag
func (o *GetInventoryAPIV2ResourcesTrendParams) bindParamTag(formats strfmt.Registry) []string {
	tagIR := o.Tag

	var tagIC []string
	for _, tagIIR := range tagIR { // explode []string

		tagIIV := tagIIR // string as string
		tagIC = append(tagIC, tagIIV)
	}

	// items.CollectionFormat: "csv"
	tagIS := swag.JoinByFormat(tagIC, "csv")

	return tagIS
}
