// Code generated by go-swagger; DO NOT EDIT.

package inventory

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kaytu-io/cli-program/pkg/api/kaytu/models"
)

// GetInventoryAPIV1ResourcesTopRegionsReader is a Reader for the GetInventoryAPIV1ResourcesTopRegions structure.
type GetInventoryAPIV1ResourcesTopRegionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetInventoryAPIV1ResourcesTopRegionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetInventoryAPIV1ResourcesTopRegionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetInventoryAPIV1ResourcesTopRegionsOK creates a GetInventoryAPIV1ResourcesTopRegionsOK with default headers values
func NewGetInventoryAPIV1ResourcesTopRegionsOK() *GetInventoryAPIV1ResourcesTopRegionsOK {
	return &GetInventoryAPIV1ResourcesTopRegionsOK{}
}

/*
GetInventoryAPIV1ResourcesTopRegionsOK describes a response with status code 200, with default header values.

OK
*/
type GetInventoryAPIV1ResourcesTopRegionsOK struct {
	Payload []*models.GitlabComKeibiengineKeibiEnginePkgInventoryAPILocationResponse
}

// IsSuccess returns true when this get inventory Api v1 resources top regions o k response has a 2xx status code
func (o *GetInventoryAPIV1ResourcesTopRegionsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get inventory Api v1 resources top regions o k response has a 3xx status code
func (o *GetInventoryAPIV1ResourcesTopRegionsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get inventory Api v1 resources top regions o k response has a 4xx status code
func (o *GetInventoryAPIV1ResourcesTopRegionsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get inventory Api v1 resources top regions o k response has a 5xx status code
func (o *GetInventoryAPIV1ResourcesTopRegionsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get inventory Api v1 resources top regions o k response a status code equal to that given
func (o *GetInventoryAPIV1ResourcesTopRegionsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get inventory Api v1 resources top regions o k response
func (o *GetInventoryAPIV1ResourcesTopRegionsOK) Code() int {
	return 200
}

func (o *GetInventoryAPIV1ResourcesTopRegionsOK) Error() string {
	return fmt.Sprintf("[GET /inventory/api/v1/resources/top/regions][%d] getInventoryApiV1ResourcesTopRegionsOK  %+v", 200, o.Payload)
}

func (o *GetInventoryAPIV1ResourcesTopRegionsOK) String() string {
	return fmt.Sprintf("[GET /inventory/api/v1/resources/top/regions][%d] getInventoryApiV1ResourcesTopRegionsOK  %+v", 200, o.Payload)
}

func (o *GetInventoryAPIV1ResourcesTopRegionsOK) GetPayload() []*models.GitlabComKeibiengineKeibiEnginePkgInventoryAPILocationResponse {
	return o.Payload
}

func (o *GetInventoryAPIV1ResourcesTopRegionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
