// Code generated by go-swagger; DO NOT EDIT.

package inventory

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetInventoryAPIV2ServicesTagParams creates a new GetInventoryAPIV2ServicesTagParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetInventoryAPIV2ServicesTagParams() *GetInventoryAPIV2ServicesTagParams {
	return &GetInventoryAPIV2ServicesTagParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetInventoryAPIV2ServicesTagParamsWithTimeout creates a new GetInventoryAPIV2ServicesTagParams object
// with the ability to set a timeout on a request.
func NewGetInventoryAPIV2ServicesTagParamsWithTimeout(timeout time.Duration) *GetInventoryAPIV2ServicesTagParams {
	return &GetInventoryAPIV2ServicesTagParams{
		timeout: timeout,
	}
}

// NewGetInventoryAPIV2ServicesTagParamsWithContext creates a new GetInventoryAPIV2ServicesTagParams object
// with the ability to set a context for a request.
func NewGetInventoryAPIV2ServicesTagParamsWithContext(ctx context.Context) *GetInventoryAPIV2ServicesTagParams {
	return &GetInventoryAPIV2ServicesTagParams{
		Context: ctx,
	}
}

// NewGetInventoryAPIV2ServicesTagParamsWithHTTPClient creates a new GetInventoryAPIV2ServicesTagParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetInventoryAPIV2ServicesTagParamsWithHTTPClient(client *http.Client) *GetInventoryAPIV2ServicesTagParams {
	return &GetInventoryAPIV2ServicesTagParams{
		HTTPClient: client,
	}
}

/*
GetInventoryAPIV2ServicesTagParams contains all the parameters to send to the API endpoint

	for the get inventory API v2 services tag operation.

	Typically these are written to a http.Request.
*/
type GetInventoryAPIV2ServicesTagParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get inventory API v2 services tag params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInventoryAPIV2ServicesTagParams) WithDefaults() *GetInventoryAPIV2ServicesTagParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get inventory API v2 services tag params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInventoryAPIV2ServicesTagParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get inventory API v2 services tag params
func (o *GetInventoryAPIV2ServicesTagParams) WithTimeout(timeout time.Duration) *GetInventoryAPIV2ServicesTagParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get inventory API v2 services tag params
func (o *GetInventoryAPIV2ServicesTagParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get inventory API v2 services tag params
func (o *GetInventoryAPIV2ServicesTagParams) WithContext(ctx context.Context) *GetInventoryAPIV2ServicesTagParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get inventory API v2 services tag params
func (o *GetInventoryAPIV2ServicesTagParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get inventory API v2 services tag params
func (o *GetInventoryAPIV2ServicesTagParams) WithHTTPClient(client *http.Client) *GetInventoryAPIV2ServicesTagParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get inventory API v2 services tag params
func (o *GetInventoryAPIV2ServicesTagParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetInventoryAPIV2ServicesTagParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
