// Code generated by go-swagger; DO NOT EDIT.

package inventory

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetInventoryAPIV2CostCompositionParams creates a new GetInventoryAPIV2CostCompositionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetInventoryAPIV2CostCompositionParams() *GetInventoryAPIV2CostCompositionParams {
	return &GetInventoryAPIV2CostCompositionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetInventoryAPIV2CostCompositionParamsWithTimeout creates a new GetInventoryAPIV2CostCompositionParams object
// with the ability to set a timeout on a request.
func NewGetInventoryAPIV2CostCompositionParamsWithTimeout(timeout time.Duration) *GetInventoryAPIV2CostCompositionParams {
	return &GetInventoryAPIV2CostCompositionParams{
		timeout: timeout,
	}
}

// NewGetInventoryAPIV2CostCompositionParamsWithContext creates a new GetInventoryAPIV2CostCompositionParams object
// with the ability to set a context for a request.
func NewGetInventoryAPIV2CostCompositionParamsWithContext(ctx context.Context) *GetInventoryAPIV2CostCompositionParams {
	return &GetInventoryAPIV2CostCompositionParams{
		Context: ctx,
	}
}

// NewGetInventoryAPIV2CostCompositionParamsWithHTTPClient creates a new GetInventoryAPIV2CostCompositionParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetInventoryAPIV2CostCompositionParamsWithHTTPClient(client *http.Client) *GetInventoryAPIV2CostCompositionParams {
	return &GetInventoryAPIV2CostCompositionParams{
		HTTPClient: client,
	}
}

/*
GetInventoryAPIV2CostCompositionParams contains all the parameters to send to the API endpoint

	for the get inventory API v2 cost composition operation.

	Typically these are written to a http.Request.
*/
type GetInventoryAPIV2CostCompositionParams struct {

	/* ConnectionGroup.

	   Connection group to filter by - mutually exclusive with connectionId
	*/
	ConnectionGroup *string

	/* ConnectionID.

	   Connection IDs to filter by - mutually exclusive with connectionGroup
	*/
	ConnectionID []string

	/* Connector.

	   Connector type to filter by
	*/
	Connector []string

	/* EndTime.

	   timestamp for end in epoch seconds
	*/
	EndTime *string

	/* StartTime.

	   timestamp for start in epoch seconds
	*/
	StartTime *string

	/* Top.

	   How many top values to return default is 5
	*/
	Top *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get inventory API v2 cost composition params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInventoryAPIV2CostCompositionParams) WithDefaults() *GetInventoryAPIV2CostCompositionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get inventory API v2 cost composition params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInventoryAPIV2CostCompositionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get inventory API v2 cost composition params
func (o *GetInventoryAPIV2CostCompositionParams) WithTimeout(timeout time.Duration) *GetInventoryAPIV2CostCompositionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get inventory API v2 cost composition params
func (o *GetInventoryAPIV2CostCompositionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get inventory API v2 cost composition params
func (o *GetInventoryAPIV2CostCompositionParams) WithContext(ctx context.Context) *GetInventoryAPIV2CostCompositionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get inventory API v2 cost composition params
func (o *GetInventoryAPIV2CostCompositionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get inventory API v2 cost composition params
func (o *GetInventoryAPIV2CostCompositionParams) WithHTTPClient(client *http.Client) *GetInventoryAPIV2CostCompositionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get inventory API v2 cost composition params
func (o *GetInventoryAPIV2CostCompositionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithConnectionGroup adds the connectionGroup to the get inventory API v2 cost composition params
func (o *GetInventoryAPIV2CostCompositionParams) WithConnectionGroup(connectionGroup *string) *GetInventoryAPIV2CostCompositionParams {
	o.SetConnectionGroup(connectionGroup)
	return o
}

// SetConnectionGroup adds the connectionGroup to the get inventory API v2 cost composition params
func (o *GetInventoryAPIV2CostCompositionParams) SetConnectionGroup(connectionGroup *string) {
	o.ConnectionGroup = connectionGroup
}

// WithConnectionID adds the connectionID to the get inventory API v2 cost composition params
func (o *GetInventoryAPIV2CostCompositionParams) WithConnectionID(connectionID []string) *GetInventoryAPIV2CostCompositionParams {
	o.SetConnectionID(connectionID)
	return o
}

// SetConnectionID adds the connectionId to the get inventory API v2 cost composition params
func (o *GetInventoryAPIV2CostCompositionParams) SetConnectionID(connectionID []string) {
	o.ConnectionID = connectionID
}

// WithConnector adds the connector to the get inventory API v2 cost composition params
func (o *GetInventoryAPIV2CostCompositionParams) WithConnector(connector []string) *GetInventoryAPIV2CostCompositionParams {
	o.SetConnector(connector)
	return o
}

// SetConnector adds the connector to the get inventory API v2 cost composition params
func (o *GetInventoryAPIV2CostCompositionParams) SetConnector(connector []string) {
	o.Connector = connector
}

// WithEndTime adds the endTime to the get inventory API v2 cost composition params
func (o *GetInventoryAPIV2CostCompositionParams) WithEndTime(endTime *string) *GetInventoryAPIV2CostCompositionParams {
	o.SetEndTime(endTime)
	return o
}

// SetEndTime adds the endTime to the get inventory API v2 cost composition params
func (o *GetInventoryAPIV2CostCompositionParams) SetEndTime(endTime *string) {
	o.EndTime = endTime
}

// WithStartTime adds the startTime to the get inventory API v2 cost composition params
func (o *GetInventoryAPIV2CostCompositionParams) WithStartTime(startTime *string) *GetInventoryAPIV2CostCompositionParams {
	o.SetStartTime(startTime)
	return o
}

// SetStartTime adds the startTime to the get inventory API v2 cost composition params
func (o *GetInventoryAPIV2CostCompositionParams) SetStartTime(startTime *string) {
	o.StartTime = startTime
}

// WithTop adds the top to the get inventory API v2 cost composition params
func (o *GetInventoryAPIV2CostCompositionParams) WithTop(top *int64) *GetInventoryAPIV2CostCompositionParams {
	o.SetTop(top)
	return o
}

// SetTop adds the top to the get inventory API v2 cost composition params
func (o *GetInventoryAPIV2CostCompositionParams) SetTop(top *int64) {
	o.Top = top
}

// WriteToRequest writes these params to a swagger request
func (o *GetInventoryAPIV2CostCompositionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ConnectionGroup != nil {

		// query param connectionGroup
		var qrConnectionGroup string

		if o.ConnectionGroup != nil {
			qrConnectionGroup = *o.ConnectionGroup
		}
		qConnectionGroup := qrConnectionGroup
		if qConnectionGroup != "" {

			if err := r.SetQueryParam("connectionGroup", qConnectionGroup); err != nil {
				return err
			}
		}
	}

	if o.ConnectionID != nil {

		// binding items for connectionId
		joinedConnectionID := o.bindParamConnectionID(reg)

		// query array param connectionId
		if err := r.SetQueryParam("connectionId", joinedConnectionID...); err != nil {
			return err
		}
	}

	if o.Connector != nil {

		// binding items for connector
		joinedConnector := o.bindParamConnector(reg)

		// query array param connector
		if err := r.SetQueryParam("connector", joinedConnector...); err != nil {
			return err
		}
	}

	if o.EndTime != nil {

		// query param endTime
		var qrEndTime string

		if o.EndTime != nil {
			qrEndTime = *o.EndTime
		}
		qEndTime := qrEndTime
		if qEndTime != "" {

			if err := r.SetQueryParam("endTime", qEndTime); err != nil {
				return err
			}
		}
	}

	if o.StartTime != nil {

		// query param startTime
		var qrStartTime string

		if o.StartTime != nil {
			qrStartTime = *o.StartTime
		}
		qStartTime := qrStartTime
		if qStartTime != "" {

			if err := r.SetQueryParam("startTime", qStartTime); err != nil {
				return err
			}
		}
	}

	if o.Top != nil {

		// query param top
		var qrTop int64

		if o.Top != nil {
			qrTop = *o.Top
		}
		qTop := swag.FormatInt64(qrTop)
		if qTop != "" {

			if err := r.SetQueryParam("top", qTop); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamGetInventoryAPIV2CostComposition binds the parameter connectionId
func (o *GetInventoryAPIV2CostCompositionParams) bindParamConnectionID(formats strfmt.Registry) []string {
	connectionIDIR := o.ConnectionID

	var connectionIDIC []string
	for _, connectionIDIIR := range connectionIDIR { // explode []string

		connectionIDIIV := connectionIDIIR // string as string
		connectionIDIC = append(connectionIDIC, connectionIDIIV)
	}

	// items.CollectionFormat: "csv"
	connectionIDIS := swag.JoinByFormat(connectionIDIC, "csv")

	return connectionIDIS
}

// bindParamGetInventoryAPIV2CostComposition binds the parameter connector
func (o *GetInventoryAPIV2CostCompositionParams) bindParamConnector(formats strfmt.Registry) []string {
	connectorIR := o.Connector

	var connectorIC []string
	for _, connectorIIR := range connectorIR { // explode []string

		connectorIIV := connectorIIR // string as string
		connectorIC = append(connectorIC, connectorIIV)
	}

	// items.CollectionFormat: "csv"
	connectorIS := swag.JoinByFormat(connectorIC, "csv")

	return connectorIS
}
