// Code generated by go-swagger; DO NOT EDIT.

package inventory

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetInventoryAPIV2ResourcesTagKeyReader is a Reader for the GetInventoryAPIV2ResourcesTagKey structure.
type GetInventoryAPIV2ResourcesTagKeyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetInventoryAPIV2ResourcesTagKeyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetInventoryAPIV2ResourcesTagKeyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /inventory/api/v2/resources/tag/{key}] GetInventoryAPIV2ResourcesTagKey", response, response.Code())
	}
}

// NewGetInventoryAPIV2ResourcesTagKeyOK creates a GetInventoryAPIV2ResourcesTagKeyOK with default headers values
func NewGetInventoryAPIV2ResourcesTagKeyOK() *GetInventoryAPIV2ResourcesTagKeyOK {
	return &GetInventoryAPIV2ResourcesTagKeyOK{}
}

/*
GetInventoryAPIV2ResourcesTagKeyOK describes a response with status code 200, with default header values.

OK
*/
type GetInventoryAPIV2ResourcesTagKeyOK struct {
	Payload []string
}

// IsSuccess returns true when this get inventory Api v2 resources tag key o k response has a 2xx status code
func (o *GetInventoryAPIV2ResourcesTagKeyOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get inventory Api v2 resources tag key o k response has a 3xx status code
func (o *GetInventoryAPIV2ResourcesTagKeyOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get inventory Api v2 resources tag key o k response has a 4xx status code
func (o *GetInventoryAPIV2ResourcesTagKeyOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get inventory Api v2 resources tag key o k response has a 5xx status code
func (o *GetInventoryAPIV2ResourcesTagKeyOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get inventory Api v2 resources tag key o k response a status code equal to that given
func (o *GetInventoryAPIV2ResourcesTagKeyOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get inventory Api v2 resources tag key o k response
func (o *GetInventoryAPIV2ResourcesTagKeyOK) Code() int {
	return 200
}

func (o *GetInventoryAPIV2ResourcesTagKeyOK) Error() string {
	return fmt.Sprintf("[GET /inventory/api/v2/resources/tag/{key}][%d] getInventoryApiV2ResourcesTagKeyOK  %+v", 200, o.Payload)
}

func (o *GetInventoryAPIV2ResourcesTagKeyOK) String() string {
	return fmt.Sprintf("[GET /inventory/api/v2/resources/tag/{key}][%d] getInventoryApiV2ResourcesTagKeyOK  %+v", 200, o.Payload)
}

func (o *GetInventoryAPIV2ResourcesTagKeyOK) GetPayload() []string {
	return o.Payload
}

func (o *GetInventoryAPIV2ResourcesTagKeyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
