// Code generated by go-swagger; DO NOT EDIT.

package inventory

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kaytu-io/cli-program/pkg/api/kaytu/models"
)

// PostInventoryAPIV1ResourcesReader is a Reader for the PostInventoryAPIV1Resources structure.
type PostInventoryAPIV1ResourcesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostInventoryAPIV1ResourcesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostInventoryAPIV1ResourcesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostInventoryAPIV1ResourcesOK creates a PostInventoryAPIV1ResourcesOK with default headers values
func NewPostInventoryAPIV1ResourcesOK() *PostInventoryAPIV1ResourcesOK {
	return &PostInventoryAPIV1ResourcesOK{}
}

/*
PostInventoryAPIV1ResourcesOK describes a response with status code 200, with default header values.

OK
*/
type PostInventoryAPIV1ResourcesOK struct {
	Payload *models.GitlabComKeibiengineKeibiEnginePkgInventoryAPIGetResourcesResponse
}

// IsSuccess returns true when this post inventory Api v1 resources o k response has a 2xx status code
func (o *PostInventoryAPIV1ResourcesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post inventory Api v1 resources o k response has a 3xx status code
func (o *PostInventoryAPIV1ResourcesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post inventory Api v1 resources o k response has a 4xx status code
func (o *PostInventoryAPIV1ResourcesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post inventory Api v1 resources o k response has a 5xx status code
func (o *PostInventoryAPIV1ResourcesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post inventory Api v1 resources o k response a status code equal to that given
func (o *PostInventoryAPIV1ResourcesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post inventory Api v1 resources o k response
func (o *PostInventoryAPIV1ResourcesOK) Code() int {
	return 200
}

func (o *PostInventoryAPIV1ResourcesOK) Error() string {
	return fmt.Sprintf("[POST /inventory/api/v1/resources][%d] postInventoryApiV1ResourcesOK  %+v", 200, o.Payload)
}

func (o *PostInventoryAPIV1ResourcesOK) String() string {
	return fmt.Sprintf("[POST /inventory/api/v1/resources][%d] postInventoryApiV1ResourcesOK  %+v", 200, o.Payload)
}

func (o *PostInventoryAPIV1ResourcesOK) GetPayload() *models.GitlabComKeibiengineKeibiEnginePkgInventoryAPIGetResourcesResponse {
	return o.Payload
}

func (o *PostInventoryAPIV1ResourcesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GitlabComKeibiengineKeibiEnginePkgInventoryAPIGetResourcesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
