// ========== DO NOT EDIT THIS FILE! AUTO GENERATED!!! =========
package query

import (
	"errors"
	"fmt"

	"github.com/kaytu-io/cli-program/pkg"
	kaytuSDK "github.com/kaytu-io/cli-program/pkg/api/kaytu"
	"github.com/kaytu-io/cli-program/pkg/api/kaytu/client/smart_query"
	"github.com/spf13/cobra"
)

var HistoryCmd = &cobra.Command{
	Use: "history",
	RunE: func(cmd *cobra.Command, args []string) error {

		client, auth, err := kaytuSDK.GetKaytuAuthClient(cmd)
		if err != nil {
			if errors.Is(err, pkg.ExpiredSession) {
				fmt.Println(err.Error())
				return nil
			}
			panic(err)
		}

		req := smart_query.NewGetInventoryAPIV1QueryRunHistoryParams()

		resp, err := client.SmartQuery.GetInventoryAPIV1QueryRunHistory(req, auth)
		if err != nil {
			return fmt.Errorf("[GetInventoryAPIV1QueryRunHistory] : %v", err)
		}

		err = pkg.PrintOutput(cmd, "GetInventoryAPIV1QueryRunHistory", resp.GetPayload())
		if err != nil {
			return fmt.Errorf("[GetInventoryAPIV1QueryRunHistory] : %v", err)
		}

		return nil

	},
}

func init() {

}
