// Code generated by go-swagger; DO NOT EDIT.

package metadata

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetMetadataAPIV1FilterParams creates a new GetMetadataAPIV1FilterParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetMetadataAPIV1FilterParams() *GetMetadataAPIV1FilterParams {
	return &GetMetadataAPIV1FilterParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetMetadataAPIV1FilterParamsWithTimeout creates a new GetMetadataAPIV1FilterParams object
// with the ability to set a timeout on a request.
func NewGetMetadataAPIV1FilterParamsWithTimeout(timeout time.Duration) *GetMetadataAPIV1FilterParams {
	return &GetMetadataAPIV1FilterParams{
		timeout: timeout,
	}
}

// NewGetMetadataAPIV1FilterParamsWithContext creates a new GetMetadataAPIV1FilterParams object
// with the ability to set a context for a request.
func NewGetMetadataAPIV1FilterParamsWithContext(ctx context.Context) *GetMetadataAPIV1FilterParams {
	return &GetMetadataAPIV1FilterParams{
		Context: ctx,
	}
}

// NewGetMetadataAPIV1FilterParamsWithHTTPClient creates a new GetMetadataAPIV1FilterParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetMetadataAPIV1FilterParamsWithHTTPClient(client *http.Client) *GetMetadataAPIV1FilterParams {
	return &GetMetadataAPIV1FilterParams{
		HTTPClient: client,
	}
}

/*
GetMetadataAPIV1FilterParams contains all the parameters to send to the API endpoint

	for the get metadata API v1 filter operation.

	Typically these are written to a http.Request.
*/
type GetMetadataAPIV1FilterParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get metadata API v1 filter params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMetadataAPIV1FilterParams) WithDefaults() *GetMetadataAPIV1FilterParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get metadata API v1 filter params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMetadataAPIV1FilterParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get metadata API v1 filter params
func (o *GetMetadataAPIV1FilterParams) WithTimeout(timeout time.Duration) *GetMetadataAPIV1FilterParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get metadata API v1 filter params
func (o *GetMetadataAPIV1FilterParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get metadata API v1 filter params
func (o *GetMetadataAPIV1FilterParams) WithContext(ctx context.Context) *GetMetadataAPIV1FilterParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get metadata API v1 filter params
func (o *GetMetadataAPIV1FilterParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get metadata API v1 filter params
func (o *GetMetadataAPIV1FilterParams) WithHTTPClient(client *http.Client) *GetMetadataAPIV1FilterParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get metadata API v1 filter params
func (o *GetMetadataAPIV1FilterParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetMetadataAPIV1FilterParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
