// Code generated by go-swagger; DO NOT EDIT.

package compliance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetComplianceAPIV1QueriesSyncReader is a Reader for the GetComplianceAPIV1QueriesSync structure.
type GetComplianceAPIV1QueriesSyncReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetComplianceAPIV1QueriesSyncReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetComplianceAPIV1QueriesSyncOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /compliance/api/v1/queries/sync] GetComplianceAPIV1QueriesSync", response, response.Code())
	}
}

// NewGetComplianceAPIV1QueriesSyncOK creates a GetComplianceAPIV1QueriesSyncOK with default headers values
func NewGetComplianceAPIV1QueriesSyncOK() *GetComplianceAPIV1QueriesSyncOK {
	return &GetComplianceAPIV1QueriesSyncOK{}
}

/*
GetComplianceAPIV1QueriesSyncOK describes a response with status code 200, with default header values.

OK
*/
type GetComplianceAPIV1QueriesSyncOK struct {
}

// IsSuccess returns true when this get compliance Api v1 queries sync o k response has a 2xx status code
func (o *GetComplianceAPIV1QueriesSyncOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get compliance Api v1 queries sync o k response has a 3xx status code
func (o *GetComplianceAPIV1QueriesSyncOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get compliance Api v1 queries sync o k response has a 4xx status code
func (o *GetComplianceAPIV1QueriesSyncOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get compliance Api v1 queries sync o k response has a 5xx status code
func (o *GetComplianceAPIV1QueriesSyncOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get compliance Api v1 queries sync o k response a status code equal to that given
func (o *GetComplianceAPIV1QueriesSyncOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get compliance Api v1 queries sync o k response
func (o *GetComplianceAPIV1QueriesSyncOK) Code() int {
	return 200
}

func (o *GetComplianceAPIV1QueriesSyncOK) Error() string {
	return fmt.Sprintf("[GET /compliance/api/v1/queries/sync][%d] getComplianceApiV1QueriesSyncOK ", 200)
}

func (o *GetComplianceAPIV1QueriesSyncOK) String() string {
	return fmt.Sprintf("[GET /compliance/api/v1/queries/sync][%d] getComplianceApiV1QueriesSyncOK ", 200)
}

func (o *GetComplianceAPIV1QueriesSyncOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
