// Code generated by go-swagger; DO NOT EDIT.

package compliance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetComplianceAPIV1ControlsControlIDSummaryParams creates a new GetComplianceAPIV1ControlsControlIDSummaryParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetComplianceAPIV1ControlsControlIDSummaryParams() *GetComplianceAPIV1ControlsControlIDSummaryParams {
	return &GetComplianceAPIV1ControlsControlIDSummaryParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetComplianceAPIV1ControlsControlIDSummaryParamsWithTimeout creates a new GetComplianceAPIV1ControlsControlIDSummaryParams object
// with the ability to set a timeout on a request.
func NewGetComplianceAPIV1ControlsControlIDSummaryParamsWithTimeout(timeout time.Duration) *GetComplianceAPIV1ControlsControlIDSummaryParams {
	return &GetComplianceAPIV1ControlsControlIDSummaryParams{
		timeout: timeout,
	}
}

// NewGetComplianceAPIV1ControlsControlIDSummaryParamsWithContext creates a new GetComplianceAPIV1ControlsControlIDSummaryParams object
// with the ability to set a context for a request.
func NewGetComplianceAPIV1ControlsControlIDSummaryParamsWithContext(ctx context.Context) *GetComplianceAPIV1ControlsControlIDSummaryParams {
	return &GetComplianceAPIV1ControlsControlIDSummaryParams{
		Context: ctx,
	}
}

// NewGetComplianceAPIV1ControlsControlIDSummaryParamsWithHTTPClient creates a new GetComplianceAPIV1ControlsControlIDSummaryParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetComplianceAPIV1ControlsControlIDSummaryParamsWithHTTPClient(client *http.Client) *GetComplianceAPIV1ControlsControlIDSummaryParams {
	return &GetComplianceAPIV1ControlsControlIDSummaryParams{
		HTTPClient: client,
	}
}

/*
GetComplianceAPIV1ControlsControlIDSummaryParams contains all the parameters to send to the API endpoint

	for the get compliance API v1 controls control ID summary operation.

	Typically these are written to a http.Request.
*/
type GetComplianceAPIV1ControlsControlIDSummaryParams struct {

	/* ConnectionGroup.

	   Connection groups to filter by
	*/
	ConnectionGroup []string

	/* ConnectionID.

	   Connection IDs to filter by
	*/
	ConnectionID []string

	/* ControlID.

	   Control ID
	*/
	ControlID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get compliance API v1 controls control ID summary params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetComplianceAPIV1ControlsControlIDSummaryParams) WithDefaults() *GetComplianceAPIV1ControlsControlIDSummaryParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get compliance API v1 controls control ID summary params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetComplianceAPIV1ControlsControlIDSummaryParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get compliance API v1 controls control ID summary params
func (o *GetComplianceAPIV1ControlsControlIDSummaryParams) WithTimeout(timeout time.Duration) *GetComplianceAPIV1ControlsControlIDSummaryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get compliance API v1 controls control ID summary params
func (o *GetComplianceAPIV1ControlsControlIDSummaryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get compliance API v1 controls control ID summary params
func (o *GetComplianceAPIV1ControlsControlIDSummaryParams) WithContext(ctx context.Context) *GetComplianceAPIV1ControlsControlIDSummaryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get compliance API v1 controls control ID summary params
func (o *GetComplianceAPIV1ControlsControlIDSummaryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get compliance API v1 controls control ID summary params
func (o *GetComplianceAPIV1ControlsControlIDSummaryParams) WithHTTPClient(client *http.Client) *GetComplianceAPIV1ControlsControlIDSummaryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get compliance API v1 controls control ID summary params
func (o *GetComplianceAPIV1ControlsControlIDSummaryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithConnectionGroup adds the connectionGroup to the get compliance API v1 controls control ID summary params
func (o *GetComplianceAPIV1ControlsControlIDSummaryParams) WithConnectionGroup(connectionGroup []string) *GetComplianceAPIV1ControlsControlIDSummaryParams {
	o.SetConnectionGroup(connectionGroup)
	return o
}

// SetConnectionGroup adds the connectionGroup to the get compliance API v1 controls control ID summary params
func (o *GetComplianceAPIV1ControlsControlIDSummaryParams) SetConnectionGroup(connectionGroup []string) {
	o.ConnectionGroup = connectionGroup
}

// WithConnectionID adds the connectionID to the get compliance API v1 controls control ID summary params
func (o *GetComplianceAPIV1ControlsControlIDSummaryParams) WithConnectionID(connectionID []string) *GetComplianceAPIV1ControlsControlIDSummaryParams {
	o.SetConnectionID(connectionID)
	return o
}

// SetConnectionID adds the connectionId to the get compliance API v1 controls control ID summary params
func (o *GetComplianceAPIV1ControlsControlIDSummaryParams) SetConnectionID(connectionID []string) {
	o.ConnectionID = connectionID
}

// WithControlID adds the controlID to the get compliance API v1 controls control ID summary params
func (o *GetComplianceAPIV1ControlsControlIDSummaryParams) WithControlID(controlID string) *GetComplianceAPIV1ControlsControlIDSummaryParams {
	o.SetControlID(controlID)
	return o
}

// SetControlID adds the controlId to the get compliance API v1 controls control ID summary params
func (o *GetComplianceAPIV1ControlsControlIDSummaryParams) SetControlID(controlID string) {
	o.ControlID = controlID
}

// WriteToRequest writes these params to a swagger request
func (o *GetComplianceAPIV1ControlsControlIDSummaryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ConnectionGroup != nil {

		// binding items for connectionGroup
		joinedConnectionGroup := o.bindParamConnectionGroup(reg)

		// query array param connectionGroup
		if err := r.SetQueryParam("connectionGroup", joinedConnectionGroup...); err != nil {
			return err
		}
	}

	if o.ConnectionID != nil {

		// binding items for connectionId
		joinedConnectionID := o.bindParamConnectionID(reg)

		// query array param connectionId
		if err := r.SetQueryParam("connectionId", joinedConnectionID...); err != nil {
			return err
		}
	}

	// path param controlId
	if err := r.SetPathParam("controlId", o.ControlID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamGetComplianceAPIV1ControlsControlIDSummary binds the parameter connectionGroup
func (o *GetComplianceAPIV1ControlsControlIDSummaryParams) bindParamConnectionGroup(formats strfmt.Registry) []string {
	connectionGroupIR := o.ConnectionGroup

	var connectionGroupIC []string
	for _, connectionGroupIIR := range connectionGroupIR { // explode []string

		connectionGroupIIV := connectionGroupIIR // string as string
		connectionGroupIC = append(connectionGroupIC, connectionGroupIIV)
	}

	// items.CollectionFormat: "csv"
	connectionGroupIS := swag.JoinByFormat(connectionGroupIC, "csv")

	return connectionGroupIS
}

// bindParamGetComplianceAPIV1ControlsControlIDSummary binds the parameter connectionId
func (o *GetComplianceAPIV1ControlsControlIDSummaryParams) bindParamConnectionID(formats strfmt.Registry) []string {
	connectionIDIR := o.ConnectionID

	var connectionIDIC []string
	for _, connectionIDIIR := range connectionIDIR { // explode []string

		connectionIDIIV := connectionIDIIR // string as string
		connectionIDIC = append(connectionIDIC, connectionIDIIV)
	}

	// items.CollectionFormat: "csv"
	connectionIDIS := swag.JoinByFormat(connectionIDIC, "csv")

	return connectionIDIS
}
