// Code generated by go-swagger; DO NOT EDIT.

package compliance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kaytu-io/cli-program/pkg/api/kaytu/models"
)

// GetComplianceAPIV1ControlsControlIDSummaryReader is a Reader for the GetComplianceAPIV1ControlsControlIDSummary structure.
type GetComplianceAPIV1ControlsControlIDSummaryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetComplianceAPIV1ControlsControlIDSummaryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetComplianceAPIV1ControlsControlIDSummaryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /compliance/api/v1/controls/{controlId}/summary] GetComplianceAPIV1ControlsControlIDSummary", response, response.Code())
	}
}

// NewGetComplianceAPIV1ControlsControlIDSummaryOK creates a GetComplianceAPIV1ControlsControlIDSummaryOK with default headers values
func NewGetComplianceAPIV1ControlsControlIDSummaryOK() *GetComplianceAPIV1ControlsControlIDSummaryOK {
	return &GetComplianceAPIV1ControlsControlIDSummaryOK{}
}

/*
GetComplianceAPIV1ControlsControlIDSummaryOK describes a response with status code 200, with default header values.

OK
*/
type GetComplianceAPIV1ControlsControlIDSummaryOK struct {
	Payload *models.GithubComKaytuIoKaytuEnginePkgComplianceAPIControlSummary
}

// IsSuccess returns true when this get compliance Api v1 controls control Id summary o k response has a 2xx status code
func (o *GetComplianceAPIV1ControlsControlIDSummaryOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get compliance Api v1 controls control Id summary o k response has a 3xx status code
func (o *GetComplianceAPIV1ControlsControlIDSummaryOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get compliance Api v1 controls control Id summary o k response has a 4xx status code
func (o *GetComplianceAPIV1ControlsControlIDSummaryOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get compliance Api v1 controls control Id summary o k response has a 5xx status code
func (o *GetComplianceAPIV1ControlsControlIDSummaryOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get compliance Api v1 controls control Id summary o k response a status code equal to that given
func (o *GetComplianceAPIV1ControlsControlIDSummaryOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get compliance Api v1 controls control Id summary o k response
func (o *GetComplianceAPIV1ControlsControlIDSummaryOK) Code() int {
	return 200
}

func (o *GetComplianceAPIV1ControlsControlIDSummaryOK) Error() string {
	return fmt.Sprintf("[GET /compliance/api/v1/controls/{controlId}/summary][%d] getComplianceApiV1ControlsControlIdSummaryOK  %+v", 200, o.Payload)
}

func (o *GetComplianceAPIV1ControlsControlIDSummaryOK) String() string {
	return fmt.Sprintf("[GET /compliance/api/v1/controls/{controlId}/summary][%d] getComplianceApiV1ControlsControlIdSummaryOK  %+v", 200, o.Payload)
}

func (o *GetComplianceAPIV1ControlsControlIDSummaryOK) GetPayload() *models.GithubComKaytuIoKaytuEnginePkgComplianceAPIControlSummary {
	return o.Payload
}

func (o *GetComplianceAPIV1ControlsControlIDSummaryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComKaytuIoKaytuEnginePkgComplianceAPIControlSummary)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
