// Code generated by go-swagger; DO NOT EDIT.

package alerting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/kaytu-io/cli-program/pkg/api/kaytu/models"
)

// NewPostAlertingAPIV1ActionSlackParams creates a new PostAlertingAPIV1ActionSlackParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAlertingAPIV1ActionSlackParams() *PostAlertingAPIV1ActionSlackParams {
	return &PostAlertingAPIV1ActionSlackParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAlertingAPIV1ActionSlackParamsWithTimeout creates a new PostAlertingAPIV1ActionSlackParams object
// with the ability to set a timeout on a request.
func NewPostAlertingAPIV1ActionSlackParamsWithTimeout(timeout time.Duration) *PostAlertingAPIV1ActionSlackParams {
	return &PostAlertingAPIV1ActionSlackParams{
		timeout: timeout,
	}
}

// NewPostAlertingAPIV1ActionSlackParamsWithContext creates a new PostAlertingAPIV1ActionSlackParams object
// with the ability to set a context for a request.
func NewPostAlertingAPIV1ActionSlackParamsWithContext(ctx context.Context) *PostAlertingAPIV1ActionSlackParams {
	return &PostAlertingAPIV1ActionSlackParams{
		Context: ctx,
	}
}

// NewPostAlertingAPIV1ActionSlackParamsWithHTTPClient creates a new PostAlertingAPIV1ActionSlackParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAlertingAPIV1ActionSlackParamsWithHTTPClient(client *http.Client) *PostAlertingAPIV1ActionSlackParams {
	return &PostAlertingAPIV1ActionSlackParams{
		HTTPClient: client,
	}
}

/*
PostAlertingAPIV1ActionSlackParams contains all the parameters to send to the API endpoint

	for the post alerting API v1 action slack operation.

	Typically these are written to a http.Request.
*/
type PostAlertingAPIV1ActionSlackParams struct {

	/* Request.

	   Request Body
	*/
	Request *models.GithubComKaytuIoKaytuEnginePkgAlertingAPISlackInputs

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post alerting API v1 action slack params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAlertingAPIV1ActionSlackParams) WithDefaults() *PostAlertingAPIV1ActionSlackParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post alerting API v1 action slack params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAlertingAPIV1ActionSlackParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post alerting API v1 action slack params
func (o *PostAlertingAPIV1ActionSlackParams) WithTimeout(timeout time.Duration) *PostAlertingAPIV1ActionSlackParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post alerting API v1 action slack params
func (o *PostAlertingAPIV1ActionSlackParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post alerting API v1 action slack params
func (o *PostAlertingAPIV1ActionSlackParams) WithContext(ctx context.Context) *PostAlertingAPIV1ActionSlackParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post alerting API v1 action slack params
func (o *PostAlertingAPIV1ActionSlackParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post alerting API v1 action slack params
func (o *PostAlertingAPIV1ActionSlackParams) WithHTTPClient(client *http.Client) *PostAlertingAPIV1ActionSlackParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post alerting API v1 action slack params
func (o *PostAlertingAPIV1ActionSlackParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the post alerting API v1 action slack params
func (o *PostAlertingAPIV1ActionSlackParams) WithRequest(request *models.GithubComKaytuIoKaytuEnginePkgAlertingAPISlackInputs) *PostAlertingAPIV1ActionSlackParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post alerting API v1 action slack params
func (o *PostAlertingAPIV1ActionSlackParams) SetRequest(request *models.GithubComKaytuIoKaytuEnginePkgAlertingAPISlackInputs) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PostAlertingAPIV1ActionSlackParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
