// Code generated by go-swagger; DO NOT EDIT.

package workspace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostWorkspaceAPIV1BootstrapWorkspaceNameCredentialReader is a Reader for the PostWorkspaceAPIV1BootstrapWorkspaceNameCredential structure.
type PostWorkspaceAPIV1BootstrapWorkspaceNameCredentialReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostWorkspaceAPIV1BootstrapWorkspaceNameCredentialReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostWorkspaceAPIV1BootstrapWorkspaceNameCredentialOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /workspace/api/v1/bootstrap/{workspace_name}/credential] PostWorkspaceAPIV1BootstrapWorkspaceNameCredential", response, response.Code())
	}
}

// NewPostWorkspaceAPIV1BootstrapWorkspaceNameCredentialOK creates a PostWorkspaceAPIV1BootstrapWorkspaceNameCredentialOK with default headers values
func NewPostWorkspaceAPIV1BootstrapWorkspaceNameCredentialOK() *PostWorkspaceAPIV1BootstrapWorkspaceNameCredentialOK {
	return &PostWorkspaceAPIV1BootstrapWorkspaceNameCredentialOK{}
}

/*
PostWorkspaceAPIV1BootstrapWorkspaceNameCredentialOK describes a response with status code 200, with default header values.

OK
*/
type PostWorkspaceAPIV1BootstrapWorkspaceNameCredentialOK struct {
	Payload int64
}

// IsSuccess returns true when this post workspace Api v1 bootstrap workspace name credential o k response has a 2xx status code
func (o *PostWorkspaceAPIV1BootstrapWorkspaceNameCredentialOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post workspace Api v1 bootstrap workspace name credential o k response has a 3xx status code
func (o *PostWorkspaceAPIV1BootstrapWorkspaceNameCredentialOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post workspace Api v1 bootstrap workspace name credential o k response has a 4xx status code
func (o *PostWorkspaceAPIV1BootstrapWorkspaceNameCredentialOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post workspace Api v1 bootstrap workspace name credential o k response has a 5xx status code
func (o *PostWorkspaceAPIV1BootstrapWorkspaceNameCredentialOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post workspace Api v1 bootstrap workspace name credential o k response a status code equal to that given
func (o *PostWorkspaceAPIV1BootstrapWorkspaceNameCredentialOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post workspace Api v1 bootstrap workspace name credential o k response
func (o *PostWorkspaceAPIV1BootstrapWorkspaceNameCredentialOK) Code() int {
	return 200
}

func (o *PostWorkspaceAPIV1BootstrapWorkspaceNameCredentialOK) Error() string {
	return fmt.Sprintf("[POST /workspace/api/v1/bootstrap/{workspace_name}/credential][%d] postWorkspaceApiV1BootstrapWorkspaceNameCredentialOK  %+v", 200, o.Payload)
}

func (o *PostWorkspaceAPIV1BootstrapWorkspaceNameCredentialOK) String() string {
	return fmt.Sprintf("[POST /workspace/api/v1/bootstrap/{workspace_name}/credential][%d] postWorkspaceApiV1BootstrapWorkspaceNameCredentialOK  %+v", 200, o.Payload)
}

func (o *PostWorkspaceAPIV1BootstrapWorkspaceNameCredentialOK) GetPayload() int64 {
	return o.Payload
}

func (o *PostWorkspaceAPIV1BootstrapWorkspaceNameCredentialOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
