// Code generated by go-swagger; DO NOT EDIT.

package resource_collection

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDParams creates a new GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDParams() *GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDParams {
	return &GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDParamsWithTimeout creates a new GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDParams object
// with the ability to set a timeout on a request.
func NewGetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDParamsWithTimeout(timeout time.Duration) *GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDParams {
	return &GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDParams{
		timeout: timeout,
	}
}

// NewGetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDParamsWithContext creates a new GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDParams object
// with the ability to set a context for a request.
func NewGetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDParamsWithContext(ctx context.Context) *GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDParams {
	return &GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDParams{
		Context: ctx,
	}
}

// NewGetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDParamsWithHTTPClient creates a new GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDParamsWithHTTPClient(client *http.Client) *GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDParams {
	return &GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDParams{
		HTTPClient: client,
	}
}

/*
GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDParams contains all the parameters to send to the API endpoint

	for the get inventory API v2 metadata resource collection resource collection ID operation.

	Typically these are written to a http.Request.
*/
type GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDParams struct {

	/* ResourceCollectionID.

	   Resource collection ID
	*/
	ResourceCollectionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get inventory API v2 metadata resource collection resource collection ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDParams) WithDefaults() *GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get inventory API v2 metadata resource collection resource collection ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get inventory API v2 metadata resource collection resource collection ID params
func (o *GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDParams) WithTimeout(timeout time.Duration) *GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get inventory API v2 metadata resource collection resource collection ID params
func (o *GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get inventory API v2 metadata resource collection resource collection ID params
func (o *GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDParams) WithContext(ctx context.Context) *GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get inventory API v2 metadata resource collection resource collection ID params
func (o *GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get inventory API v2 metadata resource collection resource collection ID params
func (o *GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDParams) WithHTTPClient(client *http.Client) *GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get inventory API v2 metadata resource collection resource collection ID params
func (o *GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithResourceCollectionID adds the resourceCollectionID to the get inventory API v2 metadata resource collection resource collection ID params
func (o *GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDParams) WithResourceCollectionID(resourceCollectionID string) *GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDParams {
	o.SetResourceCollectionID(resourceCollectionID)
	return o
}

// SetResourceCollectionID adds the resourceCollectionId to the get inventory API v2 metadata resource collection resource collection ID params
func (o *GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDParams) SetResourceCollectionID(resourceCollectionID string) {
	o.ResourceCollectionID = resourceCollectionID
}

// WriteToRequest writes these params to a swagger request
func (o *GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param resourceCollectionId
	if err := r.SetPathParam("resourceCollectionId", o.ResourceCollectionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
