// Code generated by go-swagger; DO NOT EDIT.

package resource_collection

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kaytu-io/cli-program/pkg/api/kaytu/models"
)

// GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDReader is a Reader for the GetInventoryAPIV2MetadataResourceCollectionResourceCollectionID structure.
type GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /inventory/api/v2/metadata/resource-collection/{resourceCollectionId}] GetInventoryAPIV2MetadataResourceCollectionResourceCollectionID", response, response.Code())
	}
}

// NewGetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDOK creates a GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDOK with default headers values
func NewGetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDOK() *GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDOK {
	return &GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDOK{}
}

/*
GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDOK describes a response with status code 200, with default header values.

OK
*/
type GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDOK struct {
	Payload *models.GithubComKaytuIoKaytuEnginePkgInventoryAPIResourceCollection
}

// IsSuccess returns true when this get inventory Api v2 metadata resource collection resource collection Id o k response has a 2xx status code
func (o *GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get inventory Api v2 metadata resource collection resource collection Id o k response has a 3xx status code
func (o *GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get inventory Api v2 metadata resource collection resource collection Id o k response has a 4xx status code
func (o *GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get inventory Api v2 metadata resource collection resource collection Id o k response has a 5xx status code
func (o *GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get inventory Api v2 metadata resource collection resource collection Id o k response a status code equal to that given
func (o *GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get inventory Api v2 metadata resource collection resource collection Id o k response
func (o *GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDOK) Code() int {
	return 200
}

func (o *GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDOK) Error() string {
	return fmt.Sprintf("[GET /inventory/api/v2/metadata/resource-collection/{resourceCollectionId}][%d] getInventoryApiV2MetadataResourceCollectionResourceCollectionIdOK  %+v", 200, o.Payload)
}

func (o *GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDOK) String() string {
	return fmt.Sprintf("[GET /inventory/api/v2/metadata/resource-collection/{resourceCollectionId}][%d] getInventoryApiV2MetadataResourceCollectionResourceCollectionIdOK  %+v", 200, o.Payload)
}

func (o *GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDOK) GetPayload() *models.GithubComKaytuIoKaytuEnginePkgInventoryAPIResourceCollection {
	return o.Payload
}

func (o *GetInventoryAPIV2MetadataResourceCollectionResourceCollectionIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComKaytuIoKaytuEnginePkgInventoryAPIResourceCollection)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
