AWSTemplateFormatVersion: 2010-09-09
Description: Create the Kaytu role in member accounts.
Parameters:
  KaytuManagementIAMUser:
    Description: The Kaytu iam user which has permission to your account.
    MinLength: '1'
    Type: String
  KaytuHandshakeID:
    Description: >-
      The External ID to authenticate your account - used internally by Kaytu to
      connect you with our accounts - DO NOT CHANGE THIS
    MinLength: '1'
    Type: String
Resources:
  KaytuAdditionalPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: KaytuAdditionalResourceReadOnly
      Description: A Limited policy to allow cloudquery to do its job
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Resource: '*'
            Action:
              - 'a4b:List*'
              - 'access-analyzer:Get*'
              - 'access-analyzer:List*'
              - 'access-analyzer:ValidatePolicy'
              - 'account:Get*'
              - 'account:List*'
              - 'acm-pca:Describe*'
              - 'acm-pca:Get*'
              - 'acm-pca:List*'
              - 'acm:Get*'
              - 'amplify:Get*'
              - 'amplify:List*'
              - 'apigateway:GET'
              - 'appconfig:Get*'
              - 'appconfig:List*'
              - 'appstream:Describe*'
              - 'appstream:List*'
              - 'aps:Describe*'
              - 'aps:Get*'
              - 'aps:List*'
              - 'athena:Get*'
              - 'athena:List*'
              - 'autoscaling:Describe*'
              - 'aws-portal:*Billing'
              - 'aws-portal:View*'
              - 'backup:Describe*'
              - 'backup:Get*'
              - 'backup:List*'
              - 'batch:Describe*'
              - 'batch:List*'
              - 'billing:Get*'
              - 'billing:List*'
              - 'budgets:Describe*'
              - 'budgets:View*'
              - 'cassandra:Select'
              - 'ce:Describe*'
              - 'ce:Get*'
              - 'ce:List*'
              - 'cloudformation:Describe*'
              - 'cloudformation:Get*'
              - 'cloudformation:List*'
              - 'cloudfront:Get*'
              - 'cloudfront:List*'
              - 'cloudtrail:Describe*'
              - 'cloudtrail:Get*'
              - 'cloudtrail:List*'
              - 'cloudwatch:Describe*'
              - 'cloudwatch:Get*'
              - 'cloudwatch:List*'
              - 'codeartifact:Describe*'
              - 'codeartifact:Get*'
              - 'codeartifact:List*'
              - 'codebuild:Describe*'
              - 'codebuild:Get*'
              - 'codebuild:List*'
              - 'cognito-idp:Describe*'
              - 'cognito-idp:Get*'
              - 'cognito-idp:List*'
              - 'config:Describe*'
              - 'config:Get*'
              - 'consolidatedbilling:GetAccountBillingRole'
              - 'cur:Describe*'
              - 'cur:PutReportDefinition'
              - 'cur:Get*'
              - 'directconnect:Describe*'
              - 'directconnect:List*'
              - 'dlm:Get*'
              - 'dlm:List*'
              - 'ds:DescribeConditionalForwarders'
              - 'ds:List*'
              - 'dynamodb:Describe*'
              - 'dynamodb:Get*'
              - 'dynamodb:List*'
              - 'ec2:Describe*'
              - 'ec2:Get*'
              - 'ec2:List*'
              - 'ecr:Get*'
              - 'ecr:List*'
              - 'ecs:Describe*'
              - 'ecs:Get*'
              - 'ecs:List*'
              - 'eks:Describe*'
              - 'eks:List*'
              - 'elasticache:List*'
              - 'elasticbeanstalk:List*'
              - 'elasticfilesystem:Describe*'
              - 'elasticloadbalancing:Describe*'
              - 'es:Get*'
              - 'fms:Get*'
              - 'fms:List*'
              - 'glacier:Get*'
              - 'glacier:List*'
              - 'glue:Get*'
              - 'glue:List*'
              - 'grafana:Describe*'
              - 'grafana:List*'
              - 'health:Describe*'
              - 'iam:GetSSHPublicKey'
              - 'iam:ListSSHPublicKeys'
              - 'iam:GenerateCredentialReport'
              - 'iam:GenerateServiceLastAccessedDetails'
              - 'iam:SimulateCustomPolicy'
              - 'iam:SimulatePrincipalPolicy'
              - 'imagebuilder:Get*'
              - 'imagebuilder:List*'
              - 'invoicing:GetInvoicePDF'
              - 'kinesis:DescribeStreamSummary'
              - 'kms:Describe*'
              - 'kms:Get*'
              - 'kms:List*'
              - 'lambda:Get*'
              - 'logs:Describe*'
              - 'logs:Filter*'
              - 'logs:Get*'
              - 'logs:List*'
              - 'logs:StartQuery'
              - 'logs:StopQuery'
              - 'mediastore:Describe*'
              - 'mediastore:List*'
              - 'memorydb:Describe*'
              - 'memorydb:List*'
              - 'opsworks-cm:Describe*'
              - 'opsworks-cm:List*'
              - 'opsworks:Describe*'
              - 'opsworks:Get*'
              - 'payments:GetPaymentInstrument'
              - 'payments:ListPaymentPreferences'
              - 'pricing:Describe*'
              - 'pricing:Get*'
              - 'purchase-orders:Get*'
              - 'purchase-orders:List*'
              - 'purchase-orders:View*'
              - 'ram:Get*'
              - 'redshift-serverless:Get*'
              - 'redshift-serverless:List*'
              - 'redshift:Get*'
              - 's3:ListAllMyBuckets'
              - 's3:GetBucketLocation'
              - 'savingsplans:Describe*'
              - 'secretsmanager:Describe*'
              - 'servicequotas:Get*'
              - 'servicequotas:List*'
              - 'ses:Get*'
              - 'ses:List*'
              - 'shield:Get*'
              - 'shield:List*'
              - 'sns:GetSubscriptionAttributes'
              - 'sns:List*'
              - 'ssm:Get*'
              - 'ssm:List*'
              - 'sso:List*'
              - 'states:Describe*'
              - 'states:List*'
              - 'support:Describe*'
              - 'sustainability:Get*'
              - 'tax:Get*'
              - 'tax:List*'
              - 'waf-regional:Get*'
              - 'waf-regional:List*'
              - 'waf:Get*'
              - 'waf:List*'
              - 'wafv2:Get*'
              - 'wafv2:List*'
              - 'workspaces:Describe*'
              - 'workspaces:List*'
  KaytuReadOnlyRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: KaytuOrganizationCrossAccountRole
      Description: Read Only Access for cloudquery to fetch resources from member accounts
      ManagedPolicyArns:
        - !Ref KaytuAdditionalPolicy
        - 'arn:aws:iam::aws:policy/ReadOnlyAccess'
        - 'arn:aws:iam::aws:policy/AWSOrganizationsReadOnlyAccess'
        - 'arn:aws:iam::aws:policy/AWSBillingReadOnlyAccess'
        - 'arn:aws:iam::aws:policy/AWSBudgetsReadOnlyAccess'
        - 'arn:aws:iam::aws:policy/SecurityAudit'
        - 'arn:aws:iam::aws:policy/AWSAccountActivityAccess'
      MaxSessionDuration: 28800
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref KaytuManagementIAMUser
            Action:
              - 'sts:AssumeRole'
              - 'sts:TagSession'
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref KaytuHandshakeID
Outputs:
  KaytuReadOnly:
    Value: !GetAtt
      - KaytuReadOnlyRole
      - Arn
    Description: >-
      The ARN value of the Cross-Account Role with IAM read-only permissions.
      Add this ARN value to Vantage.