name: kaytu
base: core22 # the base snap is the execution environment for this snap
version: '1.8.43' # just for humans, typically '1.2+git' or '1.3.2'
summary: Kaytu CLI
description: |
  Kaytu CLI

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # devmode # use 'strict' once you have the right plugs and slots
apps:
  kaytu:
    command: bin/cli-program
    plugs:
      - home
      - network

parts:
  kaytu:
    # See 'snapcraft plugins'
    plugin: go
    source: .
    build-snaps:
      - go

plugs:
  kaytu-home:
    interface: home
  kaytu-network:
    interface: network
