// Code generated by go-swagger; DO NOT EDIT.

package schedule

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kaytu-io/cli-program/pkg/api/kaytu/models"
)

// GetScheduleAPIV1DescribeResourceJobsPendingReader is a Reader for the GetScheduleAPIV1DescribeResourceJobsPending structure.
type GetScheduleAPIV1DescribeResourceJobsPendingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetScheduleAPIV1DescribeResourceJobsPendingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetScheduleAPIV1DescribeResourceJobsPendingOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /schedule/api/v1/describe/resource/jobs/pending] GetScheduleAPIV1DescribeResourceJobsPending", response, response.Code())
	}
}

// NewGetScheduleAPIV1DescribeResourceJobsPendingOK creates a GetScheduleAPIV1DescribeResourceJobsPendingOK with default headers values
func NewGetScheduleAPIV1DescribeResourceJobsPendingOK() *GetScheduleAPIV1DescribeResourceJobsPendingOK {
	return &GetScheduleAPIV1DescribeResourceJobsPendingOK{}
}

/*
GetScheduleAPIV1DescribeResourceJobsPendingOK describes a response with status code 200, with default header values.

OK
*/
type GetScheduleAPIV1DescribeResourceJobsPendingOK struct {
	Payload []*models.DescribeDescribeResourceJob
}

// IsSuccess returns true when this get schedule Api v1 describe resource jobs pending o k response has a 2xx status code
func (o *GetScheduleAPIV1DescribeResourceJobsPendingOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get schedule Api v1 describe resource jobs pending o k response has a 3xx status code
func (o *GetScheduleAPIV1DescribeResourceJobsPendingOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get schedule Api v1 describe resource jobs pending o k response has a 4xx status code
func (o *GetScheduleAPIV1DescribeResourceJobsPendingOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get schedule Api v1 describe resource jobs pending o k response has a 5xx status code
func (o *GetScheduleAPIV1DescribeResourceJobsPendingOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get schedule Api v1 describe resource jobs pending o k response a status code equal to that given
func (o *GetScheduleAPIV1DescribeResourceJobsPendingOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get schedule Api v1 describe resource jobs pending o k response
func (o *GetScheduleAPIV1DescribeResourceJobsPendingOK) Code() int {
	return 200
}

func (o *GetScheduleAPIV1DescribeResourceJobsPendingOK) Error() string {
	return fmt.Sprintf("[GET /schedule/api/v1/describe/resource/jobs/pending][%d] getScheduleApiV1DescribeResourceJobsPendingOK  %+v", 200, o.Payload)
}

func (o *GetScheduleAPIV1DescribeResourceJobsPendingOK) String() string {
	return fmt.Sprintf("[GET /schedule/api/v1/describe/resource/jobs/pending][%d] getScheduleApiV1DescribeResourceJobsPendingOK  %+v", 200, o.Payload)
}

func (o *GetScheduleAPIV1DescribeResourceJobsPendingOK) GetPayload() []*models.DescribeDescribeResourceJob {
	return o.Payload
}

func (o *GetScheduleAPIV1DescribeResourceJobsPendingOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
