// Code generated by go-swagger; DO NOT EDIT.

package schedule

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kaytu-io/cli-program/pkg/api/kaytu/models"
)

// GetScheduleAPIV1DescribeSourceJobsPendingReader is a Reader for the GetScheduleAPIV1DescribeSourceJobsPending structure.
type GetScheduleAPIV1DescribeSourceJobsPendingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetScheduleAPIV1DescribeSourceJobsPendingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetScheduleAPIV1DescribeSourceJobsPendingOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /schedule/api/v1/describe/source/jobs/pending] GetScheduleAPIV1DescribeSourceJobsPending", response, response.Code())
	}
}

// NewGetScheduleAPIV1DescribeSourceJobsPendingOK creates a GetScheduleAPIV1DescribeSourceJobsPendingOK with default headers values
func NewGetScheduleAPIV1DescribeSourceJobsPendingOK() *GetScheduleAPIV1DescribeSourceJobsPendingOK {
	return &GetScheduleAPIV1DescribeSourceJobsPendingOK{}
}

/*
GetScheduleAPIV1DescribeSourceJobsPendingOK describes a response with status code 200, with default header values.

OK
*/
type GetScheduleAPIV1DescribeSourceJobsPendingOK struct {
	Payload *models.GitlabComKeibiengineKeibiEnginePkgDescribeAPISource
}

// IsSuccess returns true when this get schedule Api v1 describe source jobs pending o k response has a 2xx status code
func (o *GetScheduleAPIV1DescribeSourceJobsPendingOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get schedule Api v1 describe source jobs pending o k response has a 3xx status code
func (o *GetScheduleAPIV1DescribeSourceJobsPendingOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get schedule Api v1 describe source jobs pending o k response has a 4xx status code
func (o *GetScheduleAPIV1DescribeSourceJobsPendingOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get schedule Api v1 describe source jobs pending o k response has a 5xx status code
func (o *GetScheduleAPIV1DescribeSourceJobsPendingOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get schedule Api v1 describe source jobs pending o k response a status code equal to that given
func (o *GetScheduleAPIV1DescribeSourceJobsPendingOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get schedule Api v1 describe source jobs pending o k response
func (o *GetScheduleAPIV1DescribeSourceJobsPendingOK) Code() int {
	return 200
}

func (o *GetScheduleAPIV1DescribeSourceJobsPendingOK) Error() string {
	return fmt.Sprintf("[GET /schedule/api/v1/describe/source/jobs/pending][%d] getScheduleApiV1DescribeSourceJobsPendingOK  %+v", 200, o.Payload)
}

func (o *GetScheduleAPIV1DescribeSourceJobsPendingOK) String() string {
	return fmt.Sprintf("[GET /schedule/api/v1/describe/source/jobs/pending][%d] getScheduleApiV1DescribeSourceJobsPendingOK  %+v", 200, o.Payload)
}

func (o *GetScheduleAPIV1DescribeSourceJobsPendingOK) GetPayload() *models.GitlabComKeibiengineKeibiEnginePkgDescribeAPISource {
	return o.Payload
}

func (o *GetScheduleAPIV1DescribeSourceJobsPendingOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GitlabComKeibiengineKeibiEnginePkgDescribeAPISource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
