// Code generated by go-swagger; DO NOT EDIT.

package cost_estimator

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCostEstimatorAPIV1CostAwsResourceTypeResourceIDParams creates a new GetCostEstimatorAPIV1CostAwsResourceTypeResourceIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCostEstimatorAPIV1CostAwsResourceTypeResourceIDParams() *GetCostEstimatorAPIV1CostAwsResourceTypeResourceIDParams {
	return &GetCostEstimatorAPIV1CostAwsResourceTypeResourceIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCostEstimatorAPIV1CostAwsResourceTypeResourceIDParamsWithTimeout creates a new GetCostEstimatorAPIV1CostAwsResourceTypeResourceIDParams object
// with the ability to set a timeout on a request.
func NewGetCostEstimatorAPIV1CostAwsResourceTypeResourceIDParamsWithTimeout(timeout time.Duration) *GetCostEstimatorAPIV1CostAwsResourceTypeResourceIDParams {
	return &GetCostEstimatorAPIV1CostAwsResourceTypeResourceIDParams{
		timeout: timeout,
	}
}

// NewGetCostEstimatorAPIV1CostAwsResourceTypeResourceIDParamsWithContext creates a new GetCostEstimatorAPIV1CostAwsResourceTypeResourceIDParams object
// with the ability to set a context for a request.
func NewGetCostEstimatorAPIV1CostAwsResourceTypeResourceIDParamsWithContext(ctx context.Context) *GetCostEstimatorAPIV1CostAwsResourceTypeResourceIDParams {
	return &GetCostEstimatorAPIV1CostAwsResourceTypeResourceIDParams{
		Context: ctx,
	}
}

// NewGetCostEstimatorAPIV1CostAwsResourceTypeResourceIDParamsWithHTTPClient creates a new GetCostEstimatorAPIV1CostAwsResourceTypeResourceIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCostEstimatorAPIV1CostAwsResourceTypeResourceIDParamsWithHTTPClient(client *http.Client) *GetCostEstimatorAPIV1CostAwsResourceTypeResourceIDParams {
	return &GetCostEstimatorAPIV1CostAwsResourceTypeResourceIDParams{
		HTTPClient: client,
	}
}

/*
GetCostEstimatorAPIV1CostAwsResourceTypeResourceIDParams contains all the parameters to send to the API endpoint

	for the get cost estimator API v1 cost aws resource type resource ID operation.

	Typically these are written to a http.Request.
*/
type GetCostEstimatorAPIV1CostAwsResourceTypeResourceIDParams struct {

	/* ResourceID.

	   ResourceID
	*/
	ResourceID string

	/* ResourceType.

	   ResourceType
	*/
	ResourceType string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get cost estimator API v1 cost aws resource type resource ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCostEstimatorAPIV1CostAwsResourceTypeResourceIDParams) WithDefaults() *GetCostEstimatorAPIV1CostAwsResourceTypeResourceIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get cost estimator API v1 cost aws resource type resource ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCostEstimatorAPIV1CostAwsResourceTypeResourceIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get cost estimator API v1 cost aws resource type resource ID params
func (o *GetCostEstimatorAPIV1CostAwsResourceTypeResourceIDParams) WithTimeout(timeout time.Duration) *GetCostEstimatorAPIV1CostAwsResourceTypeResourceIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get cost estimator API v1 cost aws resource type resource ID params
func (o *GetCostEstimatorAPIV1CostAwsResourceTypeResourceIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get cost estimator API v1 cost aws resource type resource ID params
func (o *GetCostEstimatorAPIV1CostAwsResourceTypeResourceIDParams) WithContext(ctx context.Context) *GetCostEstimatorAPIV1CostAwsResourceTypeResourceIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get cost estimator API v1 cost aws resource type resource ID params
func (o *GetCostEstimatorAPIV1CostAwsResourceTypeResourceIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get cost estimator API v1 cost aws resource type resource ID params
func (o *GetCostEstimatorAPIV1CostAwsResourceTypeResourceIDParams) WithHTTPClient(client *http.Client) *GetCostEstimatorAPIV1CostAwsResourceTypeResourceIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get cost estimator API v1 cost aws resource type resource ID params
func (o *GetCostEstimatorAPIV1CostAwsResourceTypeResourceIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithResourceID adds the resourceID to the get cost estimator API v1 cost aws resource type resource ID params
func (o *GetCostEstimatorAPIV1CostAwsResourceTypeResourceIDParams) WithResourceID(resourceID string) *GetCostEstimatorAPIV1CostAwsResourceTypeResourceIDParams {
	o.SetResourceID(resourceID)
	return o
}

// SetResourceID adds the resourceId to the get cost estimator API v1 cost aws resource type resource ID params
func (o *GetCostEstimatorAPIV1CostAwsResourceTypeResourceIDParams) SetResourceID(resourceID string) {
	o.ResourceID = resourceID
}

// WithResourceType adds the resourceType to the get cost estimator API v1 cost aws resource type resource ID params
func (o *GetCostEstimatorAPIV1CostAwsResourceTypeResourceIDParams) WithResourceType(resourceType string) *GetCostEstimatorAPIV1CostAwsResourceTypeResourceIDParams {
	o.SetResourceType(resourceType)
	return o
}

// SetResourceType adds the resourceType to the get cost estimator API v1 cost aws resource type resource ID params
func (o *GetCostEstimatorAPIV1CostAwsResourceTypeResourceIDParams) SetResourceType(resourceType string) {
	o.ResourceType = resourceType
}

// WriteToRequest writes these params to a swagger request
func (o *GetCostEstimatorAPIV1CostAwsResourceTypeResourceIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param resourceId
	if err := r.SetPathParam("resourceId", o.ResourceID); err != nil {
		return err
	}

	// path param resourceType
	if err := r.SetPathParam("resourceType", o.ResourceType); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
