// Code generated by go-swagger; DO NOT EDIT.

package cost_estimator

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetCostEstimatorAPIV1CostAzureResourceTypeResourceIDReader is a Reader for the GetCostEstimatorAPIV1CostAzureResourceTypeResourceID structure.
type GetCostEstimatorAPIV1CostAzureResourceTypeResourceIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCostEstimatorAPIV1CostAzureResourceTypeResourceIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCostEstimatorAPIV1CostAzureResourceTypeResourceIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /cost_estimator/api/v1/cost/azure/{resourceType}/{resourceId}] GetCostEstimatorAPIV1CostAzureResourceTypeResourceID", response, response.Code())
	}
}

// NewGetCostEstimatorAPIV1CostAzureResourceTypeResourceIDOK creates a GetCostEstimatorAPIV1CostAzureResourceTypeResourceIDOK with default headers values
func NewGetCostEstimatorAPIV1CostAzureResourceTypeResourceIDOK() *GetCostEstimatorAPIV1CostAzureResourceTypeResourceIDOK {
	return &GetCostEstimatorAPIV1CostAzureResourceTypeResourceIDOK{}
}

/*
GetCostEstimatorAPIV1CostAzureResourceTypeResourceIDOK describes a response with status code 200, with default header values.

OK
*/
type GetCostEstimatorAPIV1CostAzureResourceTypeResourceIDOK struct {
	Payload int64
}

// IsSuccess returns true when this get cost estimator Api v1 cost azure resource type resource Id o k response has a 2xx status code
func (o *GetCostEstimatorAPIV1CostAzureResourceTypeResourceIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get cost estimator Api v1 cost azure resource type resource Id o k response has a 3xx status code
func (o *GetCostEstimatorAPIV1CostAzureResourceTypeResourceIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get cost estimator Api v1 cost azure resource type resource Id o k response has a 4xx status code
func (o *GetCostEstimatorAPIV1CostAzureResourceTypeResourceIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get cost estimator Api v1 cost azure resource type resource Id o k response has a 5xx status code
func (o *GetCostEstimatorAPIV1CostAzureResourceTypeResourceIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get cost estimator Api v1 cost azure resource type resource Id o k response a status code equal to that given
func (o *GetCostEstimatorAPIV1CostAzureResourceTypeResourceIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get cost estimator Api v1 cost azure resource type resource Id o k response
func (o *GetCostEstimatorAPIV1CostAzureResourceTypeResourceIDOK) Code() int {
	return 200
}

func (o *GetCostEstimatorAPIV1CostAzureResourceTypeResourceIDOK) Error() string {
	return fmt.Sprintf("[GET /cost_estimator/api/v1/cost/azure/{resourceType}/{resourceId}][%d] getCostEstimatorApiV1CostAzureResourceTypeResourceIdOK  %+v", 200, o.Payload)
}

func (o *GetCostEstimatorAPIV1CostAzureResourceTypeResourceIDOK) String() string {
	return fmt.Sprintf("[GET /cost_estimator/api/v1/cost/azure/{resourceType}/{resourceId}][%d] getCostEstimatorApiV1CostAzureResourceTypeResourceIdOK  %+v", 200, o.Payload)
}

func (o *GetCostEstimatorAPIV1CostAzureResourceTypeResourceIDOK) GetPayload() int64 {
	return o.Payload
}

func (o *GetCostEstimatorAPIV1CostAzureResourceTypeResourceIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
