name: Go
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.4

    - name: Build
      run: GOOS=linux GOARCH=amd64 go build -o ktucli cli/main.go

    - name: Create File
      uses: finnp/create-file-action@1.0.0
      env:
        FILE_NAME: bin/buildFile
        FILE_DATA: ./ktucli
