name: Build
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: golang
    permissions: write-all
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: './go.mod'
        cache: false
        
    - name: GitHub Tag
      id : tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUBCI_TOKEN }}

    - name: Get Latest Tag
      uses: WyriHaximus/github-action-get-previous-tag@v1
      id: previousTag

    - name: update CLI version in version command
      run: |
        cd cmd
        sed -i 's+'NEW_VERSION_CLI'+${{ steps.tag_version.outputs.new_tag }}+g' version.go
        cd ..

    - name: Build
      env:
        CI_ACCESS_TOKEN: ${{ secrets.CI_ACCESS_TOKEN }}
        GITHUBCI_TOKEN: ${{ secrets.GITHUBCI_TOKEN }}
      run: |
        echo -e "machine gitlab.com login gitlab-ci-token password ${{ secrets.CI_ACCESS_TOKEN }}" > ~/.netrc
        echo -e "machine github.com login api password ${{ secrets.GITHUBCI_TOKEN }}" >> ~/.netrc
        git config --global url.https://${{ secrets.GITHUBCI_TOKEN }}@github.com/kaytu-io.insteadOf https://github.com/kaytu-io
        
        GOPRIVATE=github.com/kaytu-io CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./build/ktucli-linux-amd64 ./main.go
        GOPRIVATE=github.com/kaytu-io CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o ./build/ktucli-linux-arm64 ./main.go
        GOPRIVATE=github.com/kaytu-io CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o ./build/ktucli-windows-amd64 ./main.go
        GOPRIVATE=github.com/kaytu-io CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o ./build/ktucli-macos-amd64 ./main.go
        GOPRIVATE=github.com/kaytu-io CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o ./build/ktucli-macos-arm64 ./main.go
        export GOPRIVATE="gitlab.com/keibiengine,github.com/kaytu-io"

    - name: Create Release
      uses: ncipollo/release-action@v1.12.0
      with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          artifacts : "release.tar.gz,foo/*.txt,./build/ktucli-linux-amd64,./build/ktucli-linux-arm64,./build/ktucli-windows-amd64,./build/ktucli-macos-amd64,./build/ktucli-macos-arm64"
          draft: false
          prerelease: false

    - name: update cli version in snap
      run: |
        cd snap
        sed -i "s+VERSION_LINUX_X64+$(echo "${{ steps.tag_version.outputs.new_tag }}" | sed 's/^.//')+g" snapcraft.yaml
        cd ..

    - name: Create snap
      id: snapcraft
      uses: snapcore/action-build@v1

    - uses: snapcore/action-publish@v1
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
      with:
        snap: ${{ steps.snapcraft.outputs.snap }}
        release: stable

    - name: Set git identity
      run: |
        git config user.name 'Kaytu Developer'
        git config user.email 'dev@kaytu.io'

    - name: update cli version in homebrew
      run: |        
        cd homebrew
        sed -i "s+VERSION_HOMEBREW+$(echo "${{ steps.tag_version.outputs.new_tag }}" | sed 's/^.//')+g" kaytu.rb

        cd ..
        git clone https://x-access-token:${{ secrets.GITHUBCI_TOKEN }}@github.com/kaytu-io/homebrew-cli-tap.git
        
        cd homebrew-cli-tap
        
        git remote add homebrew-cli-tap-origin https://x-access-token:${{ secrets.GITHUBCI_TOKEN }}@github.com/kaytu-io/homebrew-cli-tap.git
        git config user.name 'Kaytu Developer'
        git config user.email 'dev@kaytu.io'

        cp ../homebrew/kaytu.rb kaytu.rb  

        git checkout main
        git add .
        git commit -a -m "update cli version"
        git push homebrew-cli-tap-origin 
        
        cd ..
        rm -rf homebrew-cli-tap

    - name: update hashes in homebrew
      run: |        
        cd homebrew
        
        sha256sum ../build/ktucli-macos-amd64 >> newHash
        cat newHash | rev | cut -c 28- | rev >> newHash 
        sed -i '1d' newHash
        sed -i 's/ *$//' newHash
        sed -i "9s/.*/$(printf '    sha256 "%s" \n' "$(cat newHash)") /" kaytu.rb
        rm -rf newHash
        
        sha256sum ../build/ktucli-macos-arm64 >> newHash
        cat newHash | rev | cut -c 28- | rev >> newHash 
        sed -i '1d' newHash
        sed -i 's/ *$//' newHash
        sed -i "17s/.*/$(printf '    sha256 "%s" \n' "$(cat newHash)") /" kaytu.rb
        rm -rf newHash

        sha256sum ../build/ktucli-linux-arm64 >> newHash
        cat newHash | rev | cut -c 28- | rev >> newHash 
        sed -i '1d' newHash
        sed -i 's/ *$//' newHash
        sed -i "25s/.*/$(printf '    sha256 "%s" \n' "$(cat newHash)") /" kaytu.rb
        rm -rf newHash
        
        sha256sum ../build/ktucli-linux-amd64 >> newHash
        cat newHash | rev | cut -c 28- | rev >> newHash 
        sed -i '1d' newHash
        sed -i 's/ *$//' newHash
        sed -i "33s/.*/$(printf '    sha256 "%s"\n' "$(cat newHash)") /" kaytu.rb
        rm -rf newHash
        
        cd ..
        
        git clone https://x-access-token:${{ secrets.GITHUBCI_TOKEN }}@github.com/kaytu-io/homebrew-cli-tap.git
        cd homebrew-cli-tap

        cp  ../homebrew/kaytu.rb kaytu.rb
        
        git remote add homebrew-cli-tap-origin https://x-access-token:${{ secrets.GITHUBCI_TOKEN }}@github.com/kaytu-io/homebrew-cli-tap.git
        git config user.name 'Kaytu Developer'
        git config user.email 'dev@kaytu.io'
        
        git checkout main
        git add .
        git commit -a -m "update hashes "
        git push homebrew-cli-tap-origin

        cd ..
        rm -rf homebrew-cli-tap
