name: Go
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.4

    - name: test
      extends: .go-cache
      only:
        - main
        - merge_requests
      services:
        - docker:dind
      variables:
        DOCKER_HOST: tcp://docker:2376
        DOCKER_TLS_CERTDIR: "/certs"
        DOCKER_TLS_VERIFY: 1
        DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
        DOCKERTEST_HOST: docker
      before_script:
        run: echo -e "machine gitlab.com login gitlab-ci-token password ${CI_JOB_TOKEN}" > ~/.netrc
      script:
        - go install gotest.tools/gotestsum@v1.8.0
        - .go/bin/gotestsum --junitfile report.xml --format testname
      allow_failure: true
      cache:
        - key: go-cache
          paths:
            - .go/pkg/mod/
            - .cache/
          policy: pull
      artifacts:
        when: always
        reports:
          junit: report.xml

    - name: Build
      run: GOOS=linux GOARCH=amd64 go build -o ktucli ./cli/main.go

    - name: Create File
      uses: finnp/create-file-action@1.0.0
      env:
        FILE_NAME: buildFile
        FILE_DATA: ./ktucli
