# This workflow will build project and create file for store build file inside a file
# new version yaml file 
name: Go
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]    
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.4

    - name: Build
      run: go build -o ktucli main.go

    - name: Create File
      uses: finnp/create-file-action@1.0.0
      env:
        FILE_NAME: "buildFile"
        FILE_DATA: ./ktucli
