name: Go
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: golang
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.4

    - name: Build
      env:
        CI_ACCESS_TOKEN: ${{ secrets.CI_ACCESS_TOKEN }}
        GITHUBCI_TOKEN: ${{ secrets.GITHUBCI_TOKEN }}
      run: |
        echo -e "machine gitlab.com login gitlab-ci-token password ${{ secrets.CI_ACCESS_TOKEN }}" > ~/.netrc
        echo -e "machine github.com login api password ${{ secrets.GITHUBCI_TOKEN }}" >> ~/.netrc
        GOPRIVATE=github.com/kaytu-io,gitlab.com/keibiengine CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./build/ktucli ./cli/main.go

    - name: Create File
      uses: finnp/create-file-action@1.0.0
      env:
        FILE_NAME: buildFile
        FILE_DATA: ./ktucli
    - name: SemanticVersion
      uses: PaulHatch/semantic-version@v5.0.3
      with:
        tag_prefix: "v"
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        version_format: "${major}.${minor}.${patch}"
        search_commit_body: true

    - name: Create Release
      uses: ncipollo/release-action@v1.12.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag: "CLI Release"
          name: Release ${{ steps.SemanticVersion.outputs.version }}
          body: ${{ steps.SemanticVersion.outputs.changelog }}
          bodyFile: ./bodyFile/body.md
          draft: false
          prerelease: false