name: Go
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.4

    - name: Build
      env:
        CI_ACCESS_TOKEN: ${{ secrets.CI_ACCESS_TOKEN }}
        GITHUBCI_TOKEN: ${{ secrets.GITHUBCI_TOKEN }}
      run: |
        echo -e "machine gitlab.com login gitlab-ci-token password ${CI_JOB_TOKEN}" > ~/.netrc
        echo -e "machine github.com login api password ${GITHUB_CI_TOKEN}" >> ~/.netrc
        GOPRIVATE=github.com/kaytu-io,gitlab.com/keibiengine GOOS=linux GOARCH=amd64 go build -o ktucli ./cli/main.go
	curl --header "PRIVATE-TOKEN: ${CI_JOB_TOKEN}" "https://gitlab.com/keibiengine/31494696/keibi-engine/go.mod?ref=main"

    - name: Create File
      uses: finnp/create-file-action@1.0.0
      env:
        FILE_NAME: buildFile
        FILE_DATA: ./ktucli
