name: Build
on:
  push:
    branches: [ "main" ]
env:
  HOMEBREW_CLI_TAP_FILE: https://github.com/kaytu-io/homebrew-cli-tap/blob/main/kaytu.rb

jobs:
  build:
    runs-on: ubuntu-latest
    environment: golang
    permissions: write-all
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.4

    - name: Build
      env:
        CI_ACCESS_TOKEN: ${{ secrets.CI_ACCESS_TOKEN }}
        GITHUBCI_TOKEN: ${{ secrets.GITHUBCI_TOKEN }}
      run: |
        echo -e "machine gitlab.com login gitlab-ci-token password ${{ secrets.CI_ACCESS_TOKEN }}" > ~/.netrc
        echo -e "machine github.com login api password ${{ secrets.GITHUBCI_TOKEN }}" >> ~/.netrc
        
        GOPRIVATE=github.com/kaytu-io,gitlab.com/keibiengine CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./build/ktucli-linux-amd64 ./main.go
        GOPRIVATE=github.com/kaytu-io,gitlab.com/keibiengine CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o ./build/ktucli-linux-arm64 ./main.go
        GOPRIVATE=github.com/kaytu-io,gitlab.com/keibiengine CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o ./build/ktucli-windows-amd64 ./main.go
        GOPRIVATE=github.com/kaytu-io,gitlab.com/keibiengine CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o ./build/ktucli-macos-amd64 ./main.go
        GOPRIVATE=github.com/kaytu-io,gitlab.com/keibiengine CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o ./build/ktucli-macos-arm64 ./main.go
        
    - name: GitHub Tag
      id : tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUBCI_TOKEN }}

    - name: Create Release
      uses: ncipollo/release-action@v1.12.0
      with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          artifacts : "release.tar.gz,foo/*.txt,./build/ktucli-linux-amd64,./build/ktucli-linux-arm64,./build/ktucli-windows-amd64,./build/ktucli-macos-amd64,./build/ktucli-macos-arm64"
          draft: false
          prerelease: false

    - name: Create snap
      id: snapcraft
      uses: snapcore/action-build@v1

    - uses: snapcore/action-publish@v1
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
      with:
        snap: ${{ steps.snapcraft.outputs.snap }}
        release: stable

    - name: Get previous tag
      uses: younited/get-previous-tag-action@v1.1.0
      id : previousTag
      with:
        match: v*

    - name: replace version
      run: |
        grep -rl ${{ steps.previousTag.outputs.previous-tag }} &HOMEBREW_CLI_TAP_FILE | xargs sed -i 's/${{ steps.previousTag.outputs.previous-tag }}/${{ steps.tag_version.outputs.new_tag }}/g'    

    - name: Add & Commit
      uses: EndBug/add-and-commit@v9.1.3
      with:
        add: ${{ HOMEBREW_CLI_TAP_FILE }}
        author_name: 'Kaytu Developer'
        author_email: dev@kaytu.io
        message: 'new version'
        committer_name: 'Kaytu Developer'
        committer_email: dev@kaytu.io
        push: true
#
#    - name: Push
#      uses: actions-js/push@v1.4
#      with:
#        github_token: ${{ secrets.CI_ACCESS_TOKEN }}
#        branch: 'test'
#        repository: kaytu-io/homebrew-cli-tap
#        directory: '.'
