# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build and write in a file
        run: go build -o ktucli main.go
               
               
      - name: Create File
        uses: finnp/create-file-action@1.0.0
        env:
          FILE_NAME: "${{home}}/buildFile.txt"
          FILE_DATA: "file content"
      
      - name: Write File
        uses: DamianReeves/write-file-action@v1.2
        with:
            path: ${{home}}/buildFile
            contents: ./ktucli
            write-mode: append
