name: Go
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.4
    - name: before build create file (1)
    - run: mkdir -p .go

    - name: before build create file (2)
    - run: mkdir -p .cache

    - name: before build (1)
      run: mkdir -p .go

    - name: before build (2)
      run: mkdir -p .cache

    - name: before build (3)
      run: echo -e "machine gitlab.com login gitlab-ci-token password ${CI_JOB_TOKEN}" > ~/.netrc

    - name: before build (4)
      run: echo -e "machine github.com login api password ${GITHUB_CI_TOKEN}" >> ~/.netrc

    - name: Build
      run: GOOS=linux GOARCH=amd64 go build -o ktucli ./cli/main.go

    - name: Create File
      uses: finnp/create-file-action@1.0.0
      env:
        FILE_NAME: buildFile
        FILE_DATA: ./ktucli
